coreruleset/coreruleset

- .github/ISSUE_TEMPLATE/01_false-positive.md
- .github/ISSUE_TEMPLATE/02_false-negative.md
- .github/ISSUE_TEMPLATE/03_bug-report.md
- .github/ISSUE_TEMPLATE/04_feature.md
> fix(migration): post migration tasks

- .github/workflows/test.yml
- tests/docker-compose.yml
- tests/regression/config.ini
This PR adds Github Actions Testing.
> feat(ci): adds github actions testing

- .github/workflows/test.yml
> fix(ci): run tests also on PRs

- README.md
> fix(docs): update badges and links in readme

- .github/workflows/test.yml
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- tests/docker-compose.yml
> fix(ci): run actions on .github change

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920180.yaml
> fix(ci): use log_contains instead

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
> Added CloudEvents content types

- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
Change to the number of CVE in the msg of rules 944120 and 944240.
> fix on the msg of rules 944120 944240

- rules/REQUEST-912-DOS-PROTECTION.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
This is the PR to include new CAPEC tagging into CRS.
It is the 2nd in a two-step PR together with https://github.com/coreruleset/coreruleset/pull/1800
See https://coreruleset.org/20200608/overhauling-the-crs-tags/ to understand the full problem and the plan to solve it.
The tagging is the work of Fernando Outeda, a student of @fzipi.
The rules->CAPEC mapping can be found here: https://docs.google.com/spreadsheets/d/13QyBN5z2BHHCx5FpjffKeaqsHdRLX_M9oLV1pja5H18/edit#gid=1965306794
This document boils down to this:
```
id capec/1000/CAPEC_child_of
912120 capec/1000/210/227/469
912130 capec/1000/210/227/469
912150 capec/1000/210/227/469
912160 capec/1000/210/227/469
912161 capec/1000/210/227/469
912170 capec/1000/210/227/469
912171 capec/1000/210/227/469
913100 capec/1000/118/224/541/310 …
```
> Added capec tags

- CHANGES
- CONTRIBUTORS.md
These changes should have been here for v3.3-RC2. I had somehow made them in the wrong branch.
> Update CHANGES and CONTRIBUTORS for 3.3

- CHANGES
> Fix CHANGES file

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
adds ~4~ 3 tests for rule 932200 (rce bypass)
> Add test for 932200

- CHANGES
- CONTRIBUTORS.md
- rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
Latest nginx error log for reference
2020/06/26 03:04:35 [error] 9993#9993: *49150 [client X.X.X.X] ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/modsecurity.d/modsecurity.conf"] [line "53"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Multipart parsing error: Multipart: Final boundary missing."] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "X.X.X.X"] [uri "/wp-json/wp/v2/media"] [unique_id "159314067511.786652"] [ref "v1671,1"], client: X.X.X.X, server: xxxxxxxxxxxxx, request: "POST /wp-json/wp/v2/media?_locale=user HTTP/2.0", host: "xxxxxxxxxxxxx", referrer: "xxxxxxxxxxxxx/wp-admin/post.php?post=6&action=edit"
2020/06/26 03:28:35 [error] …
> WordPress : Add support for upload image/media in Gutenberg Editor

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
With help of [msc_pyparser](https://github.com/digitalwave/msc_pyparser), I found two wrong indentations. This request corrects them.
> Fixed indentations

- rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
I found  method SEARCH used in Photos
> Add method "SEARCH" to allowed method

- rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
add regex in some match case
POST /xf/forums/forum-title.12345/add-thread
POST /xf/forums/forum-title.12345/save-draft
POST /xf/forums/forum-title.12345/create-thread/preview
POST /xf/forums/forum-title.12345/create-thread
POST /xf/threads/thread-title.12345/save-draft
POST /xf/posts/12345/save-inline
> add more match case in xenforo 9006120 rule

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
Adding test for pull request #1839.
> 920470: Allow # character

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
Few rules missed the PL tags, this PR added them.
> Added PL tags

- rules/REQUEST-912-DOS-PROTECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
Let SecDefaultAction decide what to do.
> Drop log from most rules

- rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
This one implements additional changes discussed in the PR #1843  proposed @ntimo .
> Ntimo v3.4/nextcloud settings overview

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942190.yaml
> Rebase PR #1794

- rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
Polishing changes in Nextcloud exclusion rules package originaly created by @kam821 , see PL #1902 .
> Polishing NextCloud exclusion rules package

- rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
> Fix FP while creating/editing a post in vanilla WordPress, v2

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920350.yaml
> Fixed regex for match IPv6 addr syntax

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Brushing up the description after the merge of #1929.
@airween: Would you mind to review this. Merge at your leisure if you think the updated description works. Sorry I had to do this, but I thought I could write it more to the point. No offense intended.
> Update description of 920350

- rules/scanners-user-agents.data
- fixing alphabetical ordering
- adding LeakIX web scanner (User-Agent: TBI-WebScanner/0.0.1 (+https://leakix.net/))
> Update for scanners-user-agents.data

- rules/lfi-os-files.data
- rules/restricted-files.data
Sending update for restricted-files.data based on real-world scan:
```
77.93.223.94 - - [25/Dec/2020:07:12:34 +0100] <censored> <censored> "GET / HTTP/1.1" 500 581 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" 908
77.93.223.94 - - [25/Dec/2020:07:12:36 +0100] <censored> <censored> "GET /wp-content/plugins/angwp/assets/dist/angwp.bundle.js HTTP/1.1" 500 251 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" 128
77.93.223.94 - - [25/Dec/2020:07:12:36 +0100] <censored> <censored> "GET / HTTP/1.1" 500 8673 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" 15559
77.93.223.94 - - …
```
> Update for restricted-files.data

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Turn them into non capturing groups as they are not used.
> Drop unneeded capture groups

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
Unfortunately this requires a backwards incompatible change, similar to what was applied to rule 920420.
> Fix false negative in rule 920480

- tests/docker-compose.yml
Second PR with TZ changes, originally from #1906
> feat(env): add timezone variable to compose

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941350.yaml
> Stop decoding things twice

- rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
- remediate FP in xf_session
- remediate FP in options update
- tighten URI regexes on options/update and pages/templates/save
- support for merging templates
- support for allowing HTML in user group's user_title
> XenForo exclusion profile improvements

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942220.yaml
Revert the PHP magic number back to the correct version as reported in #2009.
> 942220: fix magic number

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
> Drop trailing period as done in other rules

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
As discussed in issue #2001 we want to move the rule 920300 from PL2 to PL3.
> Move rule 920300 from PL2 to PL3

- rules/REQUEST-913-SCANNER-DETECTION.conf
- tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913100.yaml
Fix for issue #1969 by doing simple whitelist, as discussed on Monthly Chat Agendas of January.
> Whitelist for YAM package manager

- rules/crawlers-user-agents.data
Adding new crawler into crawlers-user-agents.data:
`User-Agent: mozilla/5.0 ecairn-grabber/1.0 (+http://ecairn.com/grabber)`
Fixing alphabetical ordering of file crawlers-user-agents.data. 
This affects rule 913102 .
> Adding new crawler, fixing alphabetical ordering

- rules/RESPONSE-955-WEB-SHELLS.conf
received on a customer Drupal (exploiting drupalgeddon). Webshell HTML content:
```html
<form method='POST' enctype='multipart/form-data'><input type='file'name='file' /><input type='submit' value='file' /></form>AnonymousFox
```
> Add AnonymousFox PHP webshell

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
When I saw my merged PR #2013 I spotted a typo which I fix in this PR. I forgot to set the correct PL var.
> Fix PL typo

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
as reported here https://www.bleepingcomputer.com/news/security/phps-git-server-hacked-to-add-backdoors-to-php-source-code/
> Block zerodium PHP backdoor: restricted header user-agentt

- INSTALL
- plugins/README.md
This contains the plugins folder and an extended INSTALL file with additional includes and a brief explanations of what CRS plugins are.
> Includes for plugins

- rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
- rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
- rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
- rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
> Replaced ARGS by ARGS_GET in rules in phase:1

- rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf
This PR fixies:
- FPs with Prime Subject Check extension
- https://github.com/coreruleset/coreruleset/issues/2043
> Fixes for few phpBB FPs

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml
- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941181.yaml
Moved --> keyword from 941180 (PL1) into new stricter sibling rule 941181 (PL2) #2060
Updated 941180 to include a negative test for -->
Added tests for 941181
Replaces PR2082
> Moved --> keyword from 941180 (PL1) into new stricter sibling rule 941181 (PL2) #2060

- util/change-version/README.md
- util/change-version/README.txt
- util/change-version/change-version.py
> Added change version helper tool

- tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921110.yaml
This PR adds to tests to show that the FP in issue #2054 has been resolved. And it's always good to have tests :-)
> Add two tests for fp 921110 request smuggling

- .gitignore
- tests/docker-compose.yml
- tests/logs/modsec2-apache/README.md
- tests/logs/modsec3-nginx/README.md
- tests/logs/modsec3-nginx/nginx/README.md
- tests/regression/README.md
- tests/regression/config.ini
Also moves logs one level up to simplify navigation.
Fixes #2096.
> Added directories needed for volume mounts to Git.

- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-910-IP-REPUTATION.conf
> A small cosmetic fix: added missing space after comment mark

- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
According to documentation, `@pmFromFile` / `@pm` is doing case-**in**sensitive match so `t:lowercase` is not needed.
> Little performance fixies

- .github/FUNDING.yml
> feat(button): add github funding button

- .github/FUNDING.yml
Change to a redirect from the coreruleset site.
> fix(url): change to coreruleset domain

- .github/workflows/go-ftw.yml
This PR runs `go-ftw` in a new test. It should *not* be required to pass before merge, while we test it works properly.
> feat(ftw): initial go-ftw running version

- rules/scanners-user-agents.data
While doing the release I noticed this branch. I don’t know why it was not turned into a pull request. It looks like it would be worth including it after a short review.
> scanners: add QQGameHall UA

- rules/crawlers-user-agents.data
I believe this addresses issue #2146
> Add two new crawler User-Agent strings

- rules/scanners-user-agents.data
Adding burpcollaborator as an scanner.
> add burpcollaborator to scanner user agents

- crs-setup.conf.example
Thanks @fzipi for pointing [this](https://github.com/coreruleset/coreruleset/issues/2161#issuecomment-882517085).
> Added some note to the default allowed_request_content_type settings

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932100.yaml
> fix(test): remove broken test 932100-3

- KNOWN_BUGS.md
> docs: update links and format of known bugs

- rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf
> Fix for phpBB FP

- SPONSORS.md
Appearing in a file SPONSORS is one of the sponsoring benefits we are giving our sponsors.
> New file SPONSORS.md

- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
this replaces #2052 and adds comments and tests
> replaces #2052 RCE bypass uninitialized vars

- CONTRIBUTORS.md
Thank you for inviting me to add myself to the contributors file.
> Add Paul Beckett to contributors file

- rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
I believe this resolves issue #2199
> Amend rule 9004110 to use newer format for var

- CONTRIBUTING.md
- SECURITY.md
- crs-setup.conf.example
Just updating old links in docs.
> fix(links): update old links

- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf
- rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
As #2236 contains the new tool, I ran it against the current CRS, and found few issues. This PR fixes them.
> Aligned the actions into right order

- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933111.yaml
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933190.yaml
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933200.yaml
Add test cases for 933111, 933190 and 933200
> Add test cases

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932180.yaml
This PR adds two positive and one negative test for rule 932180.
> Add testfile 932180

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932130.yaml
Add positive and negative tests for rule 932130
> Add positive and negative tests for rule 932130

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
Add positive and negative tests for rule 932160
> Add positive and negative tests for rule 932160

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932150.yaml
Add positive and negative tests for rule 932150
> Add positive and negative tests for rule 932150

- rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
Using the example as put in the comments, I get errors: the ID is a duplicate and the rule isn't parsed.
I've chosen a new ID (not sure how this is normally done) and changed the configuration line to one that works for me.
> NextCloud example in comments fix

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920121.yaml
> Add Tests for Rule 920121

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932171.yaml
This PR adds 2 positive testcases for Shellshock rule 932171
> Add 2 positive testcases for 932171

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932105.yaml
Added a true positive and a true negative tests for rule 932105.
> Added tests for rule 932105

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932190.yaml
Test cases for rule 932190, original author is @franbuehler.
> This PR adds two positive and a negative testcase for rule 932190.

- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> Fixing Sybase FP

- tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921180.yaml
Based on original tests by @jptosso in #2267.
> Add tests for 921180

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> ci: add PR template example

- rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
> WordPress exclusions: Fix for FP

- rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf
One FP catched in real-world + fix ordering of `ruleRemoveTargetById` actions.
> phpMyAdmin exclusions: Fix for FP

- rules/REQUEST-913-SCANNER-DETECTION.conf
I think this capec better suits web crawlers.
OLD: https://capec.mitre.org/data/definitions/310.html
NEW: https://capec.mitre.org/data/definitions/150.html
> Fix capec for crawlers

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
This fixes #1867, which has been open much too long.
Decision for this shift was taken back at meeting in Feb 2021: https://github.com/coreruleset/coreruleset/issues/1992#issuecomment-771133088.
> Move 941120 from PL1 to PL2

- tests/regression/utils/data/popularUAs.data
I'm mostly curious if this will trigger any rules.
> Add a Chrome and Firefox version 100 UA

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Fixes remainings from path change.
> fix(path): update path in util to subdirectory

- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
as discussed in the coreruleset-dev slack channel.
I'm intentionally not sharing other information.
> Fix 933210 Regex

- rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf
- fix for FP on PL4
- reordering `ctl:ruleRemoveTargetById` by rule IDs
> Fix for phpBB FP on PL4

- rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf
- Fixing one FP (unfortunately don't know which section of phpBB triggered it).
- Adding rules skipping in phase 4
> phpBB: Fixing FP and package deactivation

- tests/docker-compose.yml
> feat(ci): enable checking json response

- rules/REQUEST-901-INITIALIZATION.conf
Rename setup.conf to crs-setup.conf
> REQUEST-901-INITIALIZATION.conf: fix typo in crs config file name

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942230.yaml
- util/regexp-assemble/data/942230.data
Added regexp-assemble file for rule
Fixes #2230
> Fixed false negative for 942230

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
Related to https://github.com/coreruleset/coreruleset/pull/2360
This is PR 1 of 4 that replace #2360.
> Added additional tests for 920120

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
Related to https://github.com/coreruleset/coreruleset/pull/2360
This is PR 2 of 4 that replace https://github.com/coreruleset/coreruleset/pull/2360.
> Cleaned up quoting in tests for 920120

- .yamllint.yml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920100.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920272.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920290.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920430.yaml
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932100.yaml
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932101.yaml
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942190.yaml
This PR should fix #2374.
- updated config to reflect spacing change
- updated files so we fix the mentioned spacing
> Fix yamllint

- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- util/regexp-assemble/data/920521.data
Removed obsolete comment from regex data file
This addresses the question from #2357.
> Updated comment on 920520 to explain the value of the header length check

- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932190.yaml
I have a couple of questions that I hope @theMiddleBlue can answer. Until then, this PR will remain in draft state.
> Backslashes 932190

- .github/workflows/lint.yaml
> fix(ci): update secrules-parsing module

- tests/docker-compose.yml
Counterpart to https://github.com/coreruleset/modsecurity-crs-docker/pull/66.
> Added support for plugins to docker-compose

- SECURITY.md
- Update security policy to include release verification
- Add pointer to the sandbox to verify bypasses
> docs: update policy to include signed releases

- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
> 933110: update owasp.org vulnerability URL

- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- tests/regression/tests/REQUEST-944-APPLICATION-ATTACK-JAVA/944260.yml
missing detection of spring rce payloads
> Spring RCE missing payloads

- tests/regression/CRS_Tests.py
> Fixed configuration key 'log_location_linux'

- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- tests/regression/tests/REQUEST-931-APPLICATION-ATTACK-RFI/931130.yaml
- ~added t:urlDecodeUni to prevent bypass~
- added basic auth pattern to the regex
> fix bypass 931130

- README.md
> minor correction

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932115.yaml
Set the correct `test_title` of the test case 932115-7 (was: 942260-17).
> Fix test_title of the test case

- tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934130.yaml
> fix regression tests 934130-6 title duplicate

- CHANGES
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/web-shells-php.data
- tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913102.yaml
- tests/regression/tests/REQUEST-949-BLOCKING-EVALUATION/949110.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
- tests/regression/tests/RESPONSE-959-BLOCKING-EVALUATION/959100.yaml
- util/change-version/change-version.py
- util/crs-rules-check/rules-check.py
- util/find-rules-without-test/find-rules-without-test.py
> Fix: Typos across the entire project as reported by codespell

- CONTRIBUTORS.md
Thank you for the work you do. I am happy to contribute as well, when I can.
@dune73 suggested that I add my name to the list of developers, so here is my application to do so :-)
> Move Simon Studer to list of developers.

- util/regexp-assemble/lib/operators/assembler.py
- util/regexp-assemble/lib/processors/assemble.py
- util/regexp-assemble/lib/processors/processor.py
- util/regexp-assemble/lib/processors/template.py
Fixing types for regex assembler.
> fix(regexp-assemble): Fix types

- util/regexp-assemble/README.md
- util/regexp-assemble/lib/context.py
- util/regexp-assemble/lib/operators/assembler.py
- util/regexp-assemble/lib/operators/parser.py
- util/regexp-assemble/lib/operators/updater.py
- util/regexp-assemble/lib/processors/assemble.py
- util/regexp-assemble/lib/processors/include.py
- util/regexp-assemble/lib/processors/processor.py
- util/regexp-assemble/regexp-assemble.py
- util/regexp-assemble/tests/assembler_test.py
- util/regexp-assemble/tests/fixtures.py
- util/regexp-assemble/tests/preprocessor_test.py
The include preprocessor gives us the ability to reduce repetitions
across data files.
> feat(regexp-assemble): Add include preprocessor

- CHANGES.md
> docs: update changelog file to markdown

- CHANGES.md
> fix(docs): fix markdown in changes

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
- util/regexp-assemble/data/942120.data
Block attempts to use various SQL operators, some specific to certain database management systems.
> Add various SQL operators for 942120

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942290.yaml
- util/regexp-assemble/data/942290.data
> nosqli additional operators and fix checks for json body

- util/regexp-assemble/lib/operators/updater.py
> fix(regexp-assemble): fix path composition when updating

- rules/crawlers-user-agents.data
- rules/scripting-user-agents.data
1. Add some popular http client library into scripting-user-agents.data
```
aiohttp/
Go http package
Go 1.1 package http
Go-http-client/
python-httpx/
unirest-java/
```
2. Add some popular scraping framework into crawlers-user-agents.data
```
ACHE/
colly -
crawler4j
heritrix/
Mechanize
NutchCVS/
pyspider/
Scrapy/
```
> add some popular http library & scraping framework

- .yamllint.yml
> fix: update ignore on yamllint

- rules/php-variables.data
- update list with comments on where the data comes from
- added deprecation comments on variables
Closes #2651
> fix(list): update php-variables

- rules/web-shells-php.data
> Update for web-shells-php.data

- rules/unix-shell.data
- just add the remaining command `expr`
- still need to figure it out what to do with `alias`
> fix(list): update unix-shell with expr

- .github/ISSUE_TEMPLATE/02_false-negative.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> chore: fix github PR and issue templates

- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942521.yaml
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942522.yaml
This PR resolves BB issue https://github.com/coreruleset/coreruleset/issues/2707. 
The missing sqli coverage was already fixed (see issue) and this PR only adds two additional tests in two rules to prove this.
> feat(sqli test): BB testcases for 942521 and 942522 added

- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
This PR resolves BB issue #2703. The missing sqli coverage was already fixed (see issue) and this PR only adds an additional test to prove this.
> feat(sqli test): BB testcase for 942120 added

- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942520.yaml
This PR resolves BB issue https://github.com/coreruleset/coreruleset/issues/2704. The missing sqli coverage was already fixed (see issue) and this PR only adds an additional test to prove this.
> feat(sqli test): BB testcase for 942520 added

- crs-setup.conf.example
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- tests/regression/tests/REQUEST-931-APPLICATION-ATTACK-RFI/931130.yaml
Relates to **YJGXRICC**
Associated issue: #2726 
---
This PR:
- Adds detection for `url:file://` to rule 931130
- Adds a test to detect `url:file://`
> Add url file 931130

- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933200.yaml
- util/regexp-assemble/data/933200.data
Relates to **N330BFLK**
Associated issue: #2722
---
This PR:
- Decompiles the regular expression pattern of rule 933200
- Adds the new pattern `bzip2` to resolve N330BFLK
- Adds several new tests for rule 933200
> Php wrappers

- util/regexp-assemble/data/932130.data
Use ##!, not # to comment in data files
> fix: use correct comments in data file

- README.md
> ci: fix version in badge

- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/iis-errors.data
- tests/regression/tests/RESPONSE-954-DATA-LEAKAGES-IIS/954120.yaml
Update IIS errors and rule 954120 to use the error file.
Fixes #2631.
> feat(iis): update iis errors

- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- util/regexp-assemble/data/932210.data
- updates sqlite cli commands list.
Fixes #2800
> fix(932210): update sqlite cli commands list

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942530.yaml
This PR resolves BB issue #2734.
False positives are likely, therefore I added this rule to PL3.
I didn't found a similar rule, that's why I wrote a new rule.
I also added a test.
> fix(sqli): add RKJU2TTV finding

- .github/workflows/go-ftw.yml
> ci: fix go-ftw organization change

- util/regexp-assemble/lib/operators/assembler.py
- util/regexp-assemble/lib/processors/template.py
- util/regexp-assemble/regexp-assemble.py
- util/regexp-assemble/tests/assembler_test.py
- util/regexp-assemble/tests/fixtures.py
- util/regexp-assemble/tests/preprocessor_test.py
- initially just write test proving that recursive includes don't work.
> fix(regexp-assemble): recursive includes

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942320.yaml
- util/regexp-assemble/data/942320.data
This PR closes two bypasses from Shivam's bypass list by adding two functions to postgres PL1 rule 942320.
* closes #2910
* closes #2912
> fix(sqli) - add 2 postgres functions

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-910-IP-REPUTATION.conf
- rules/REQUEST-912-DOS-PROTECTION.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
This PR collects few small commits, see the messages at the commits.
> fix(ruleset scoring and tagging): Fix PL related issues in v3.3./dev

- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930110.yaml
> added ; to rule 930110 to Fix issue 2881

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942110.yaml
> fix(RQ1R4RCP): add REQUEST_FILENAME to 942110

- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934160.yaml
- util/regexp-assemble/data/934160.data
- util/regexp-assemble/data/include/js-truthy-values.data
Added a new rule that fixes #2843 by checking for while loops with truthy conditions.
> fix(0TECJUUS): New rule for NodeJS DoS attack vectors 

- util/regexp-assemble/data/941130.data
fix: 941130.data Simplify 941130.data by creating prefix
> Simplify 941130.data by creating prefix

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
according to #2922 
@lifeforms
> FIX: moved rule 942101 to PL2

- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
fixed setvars and tags with the correct PL value.
fixed unnecessary PL set tags  if nolog is used
> FIX: PL setvars and tags

- util/regexp-assemble/data/942350.data
> fix(regex): improved the file data for 942350

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920100.yaml
PR adds a status page test for rule 920100 (a new test which only triggers this specific rule).
> Add status page test for rule 920100

- CONTRIBUTORS.md
@dune73 suggested creating this PR to discuss the possibility of giving me commit rights to the CRS organisation.
> chore: add Karel to 'Developers'

- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932240.yaml
due to many false positive, we need to remove ARGS_NAMES from variable list of 932240
> fix(932240): remove ARGS_NAME from variables

- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
> fix(paranoialevel) Fixed PL related tag/variable pairs at rule 932240

- util/regexp-assemble/data/942200.data
This PR disassembles data file for 942200.
I tested it, output is the same as we have in the current rule.
Closes #2857.
> fix(regex 942200) - disassembled data file

- tests/regression/tests/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION/943100.yaml
This PR adds a test that only triggers 943100.
> feat(test) - add status page test for 943100

- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942170.yaml
This PR adds a testcase 942170-4 that only triggers this rule.
> feat(test) - add status page test for 942170

- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941400.yaml
This PR adds a status page test 941400-7 that only triggers this rule.
> feat(test) - Add status page test 941400

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> fix(942540): fix scoring variable

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920340.yaml
PR adds a status page test for rule 920340 (a new test which only triggers this specific rule).
> Add status page test for rule 920340

- util/regexp-assemble/data/942290.data
> fix(regex): fix data file for 942290

- util/regexp-assemble/data/942170.data
> fix(regex): fix data file for 942170

- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941310.yaml
This PR adds the status page test 941310-12. This new test only triggers one rule.
> feat(test) - add status page test for 941310

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932230.yaml
> test: add for BB BBBZARPI

- util/regexp-assemble/data/942362.data
Improved regex data file for rule 942362
> fix(regex): fix data file for regex 942362

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- util/regexp-assemble/data/942210.data
This PR reworks and re-expresses the regex data file for rule 942210.
Resolves issue #2858.
> feat(942210): rework and reexpress regex data file

- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941200.yaml
This PR adds a status page test 941200-4 that only triggers this rule.
> feat(test) - add status page test for 941200

- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941170.yaml
This PR adds a status page test 941170-5 that only triggers this one rule.
> feat(test) - add status page test for 941170

- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941140.yaml
This PR adds a status page test that only triggers this one rule.
> feat(test) - add status page test for 941140

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
New test triggering only 932160 (for status page).
> new test 932160-8

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
> tests: add coverage for BB EBIDJ91T and MKXQCJMX

- regex-assembly/942260.ra
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
fix 942260 update 942260.data to utilise crs-toolchain format
> feat(942260): update .ra to utilise crs-toolchain formats, and rebuild

- regex-assembly/932240.ra
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932240.yaml
Fixes failing curl tests calls for S01X1GRV.
> fix: add missing empty variable evasion techniques

- regex-assembly/942180.ra
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
fix 942180 : Update 942180.data and rebuild rule 942180 using crs-toolchain
Needed to manually remove :space: from assembled rule due to apache incompatibility with CRS toolchain assembled rule.
> fix(942180): update 942180.ra and rebuild rule 942180

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
PR adds a status page test for rule 920100 (a new test which only triggers this specific rule).
> Add status page test for rule 920470

- .github/ISSUE_TEMPLATE/01_false-positive.md
- .github/ISSUE_TEMPLATE/02_false-negative.md
- .github/ISSUE_TEMPLATE/03_bug-report.md
- .github/ISSUE_TEMPLATE/04_feature.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- update github labels after adding emojis
- update text in issues to include also where to get help and support.
> fix: update github template labels

- regex-assembly/942280.ra
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
(sorry for the fork branch name) refer to #2929
> fix(regex): fix data file for 942280 rule

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920340.yaml
> fix: remove test 920340-2, rename 920340-3 to 920340-2

- CONTRIBUTING.md
> docs: Add section about leaving audit log format unchanged to CONTRIBUTING.md

- rules/lfi-os-files.data
- tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930120.yaml
Fixes BB issue YM9WT5NU by disallowing access to /tmp/ completely.
> fix: disallow access to /tmp/

- .github/ISSUE_TEMPLATE/01_false-positive.md
- .github/ISSUE_TEMPLATE/02_false-negative.md
I have rewritten the two issue templates from scratch. I thought it was necessary to make it clearer what we really need.
> docs: Rewrite issue templates for false positives and false negatives

- .github/workflows/test.yml
- regex-assembly/951240.ra
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
> fix(FP): PostgreSQL error messages

- util/crs-rules-check/rules-check.py
Only a typo fix - thanks @M4tteoP.
> fix(typo): Typo fix

- rules/restricted-files.data
Config file is app/config/parameters.php for PrestaShop 1.7+
This files contain sensitive data: database access, private keys
> feat: Add PrestaShop config file

- crs-setup.conf.example
- tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921150.yaml
PR adds a status page test for rule 921150 (a new test which only triggers this specific rule).
> feat: Add status page test for rule 921150

- util/fp-finder/spell.sh
this could be useful for our lists, it checks English words on .data files that could lead to FPs
> Util to find English words on .data

- CONTRIBUTING.md
Similar as [crs-doc #84](https://github.com/coreruleset/documentation/pull/84).
> docs(guideline): Add chain rule commenting guidance

- rules/sql-errors.data
**Source:-** https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/errors.xml
The errors are taken in serial order from the source file.
> feat: updated `sql-errors.data`

- rules/web-shells-php.data
Laudanum is a popular collection of web shells. I added it's PHP webshells and WordPress plugin. 
**Source:-** https://sourceforge.net/projects/laudanum/
The [Seclists](https://github.com/danielmiessler/SecLists.git) project also includes Laudanum.
> feat: updated `web-shells-php.data`

- SPONSORS.md
- updated sponsors list
- sorted alphabetically
> docs: update sponsors

- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Description for SQLi hex evasion detection rule
> chore: Added description for rule 942450

- regex-assembly/942440-chain1.ra
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- move chained regex to regex-assembly format
- update docs and add more context.
> feat(942440): move chained regex to regex-assembly

- regex-assembly/942300.ra
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Fixes #2943.
We can probably add more comments on the intended matching of each of the classes in the file 🤔
> feat(942300): improve regex-assembly format

- rules/restricted-files.data
> fix: fixed minor typo in comment

- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Prepare v4.0.0-rc2:
* changed copyright year
* changed version in header comments
* changed `ver` actions' value
> chore: Prepare v4.0.0-rc2

- rules/REQUEST-921-PROTOCOL-ATTACK.conf
Changed the correct rule id in rule's comment. Resolves #3329.
> docs: Typo fix: change correct rule id

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932175.yaml
> feat: new isolated test 932175-9 (932175 PL1) (Christian Folini)

- tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930100.yaml
> feat: new isolated test 930100-4 (930100 PL1) (Christian Folini)

- tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934170.yaml
> feat: new isolated test 934170-3 (934170 PL1) (Christian Folini)

- .github/workflows/test.yml
The tests should also run when scripts in `util` change.
> chore: run tests when `util` changes

- tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921160.yaml
> feat: new isolated test 921160-6 (921160 PL1) (Christian Folini)

- tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942560.yaml
> feat: new isolated test 942560-2 (942560 PL1) (Christian Folini)

- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941130.yaml
> feat: new isolated test 941130-19 (941130 PL1) (Christian Folini)

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920290.yaml
> feat: new isolated test 920290-4 (920290 PL1) (Christian Folini)

- rules/web-shells-php.data
- tests/regression/tests/RESPONSE-955-WEB-SHELLS/955100.yaml
> feat: added new webshells and tests (955100 PL1) (Jozef Sudolski)

- crs-setup.conf.example
This brings an additional notice to the comment of 900300.
This fixes #3144.
> fix: reword comment (900300 config) (Christian Folini)

- rules/restricted-files.data
Add .vscode to restricted-files.data
Fixes #3463
> feat: add .vscode to restricted-files.data (930130 PL1)

- rules/REQUEST-922-MULTIPART-ATTACK.conf
- tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922100.yaml
Fix for [this](https://github.com/coreruleset/coreruleset/issues/3114#issuecomment-1407350626) issue.
Label `v4` can be removed from issue https://github.com/coreruleset/coreruleset/issues/3114 after this is merged (but do NOT close that issue).
Fixes: #3118
> fix: Unwanted match of charset (922100 PL1)

- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933150.yaml
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
Extracted and rearranged test fixes initially provided via https://github.com/coreruleset/coreruleset/pull/3201 by @theMiddleBlue.
> fix(test): 933150/60 tests and descriptions

- crs-setup.conf.example
As per [CRS Meeting Oct 2023](https://github.com/coreruleset/coreruleset/issues/3280#issuecomment-1744217375).
Also see documentation PR https://github.com/coreruleset/documentation/pull/113
Fixes #2517
> feat: remove SecCollectionTimeout from crs-setup.conf

- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
> chore: update dev branch version to 4.0.1-dev

- .github/create-changelog-prs.py
This commit reduces the probability of merge conflicts in changelog PRs by using an existing changelog PR as base, if possible.
When the script creates more than one changelog PR, every new PR uses the previously created PR as base.
> feat: base changelog PRs on existing changelog PRs

- .github/workflows/update-changelog.yaml
Haven't found any explanation as to what changed w.r.t. to permissions. Since I have no clue, let's start with full permissions and then narrow them down.
> chore: try to give job full access

- .github/workflows/check-pr-title.yaml
- .github/workflows/lint.yaml
- .github/workflows/nightly.yml
- .github/workflows/stale.yml
- .github/workflows/test.yml
- .github/workflows/update-changelog.yaml
I've also updated the patterns of the allowed actions to allow for pinning hashes.
> chore(deps): update workflow actions

- CONTRIBUTORS.md
- SECURITY.md
- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
- update file text with `4.1.0`
> chore: release v4.1.0

- regex-assembly/933100.ra
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
This PR disassembles the rule 933100 without changing its behaviour.
After merging this PR, I'll solve the issue #3616 and extend the regex.
I hope this two step approach makes the changes easier to understand.
> feat: disassemble php rule (933100 PL1)

- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
- update files post 4.2.0 release
> chore: post release add 4.3.0-dev

- regex-assembly/951120.ra
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
Fixing FPs with:
`Oracle (OCI) driver`
`warning ... /ancora_themes/ ...`
> fix: resolving more FPs with Oracle error messages (951120 PL1)

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
> fix: fix FP test to fail when condition not met

- tests/regression/tests/RESPONSE-980-CORRELATION/980170.yaml
Refs https://github.com/coreruleset/go-ftw/issues/141
> test: use `retry_once` in phase 5 rule test

- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932171.yaml
This is covered in test for rule `932170`.
> fix: fixing test typo

- CHANGES.md
- CONTRIBUTORS.md
- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
> chore: new release v4.3.0

- tests/docker-compose.yml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920100.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920272.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951110.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951120.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951130.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951140.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951150.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951160.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951170.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951180.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951190.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951200.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951210.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951220.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951230.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951240.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951250.yaml
- tests/regression/tests/RESPONSE-951-DATA-LEAKAGES-SQL/951260.yaml
- tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
- tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953120.yaml
- tests/regression/tests/RESPONSE-954-DATA-LEAKAGES-IIS/954100.yaml
- tests/regression/tests/RESPONSE-954-DATA-LEAKAGES-IIS/954120.yaml
- tests/regression/tests/RESPONSE-955-WEB-SHELLS/955100.yaml
- tests/regression/tests/RESPONSE-959-BLOCKING-EVALUATION/959100.yaml
Update all tests to produce proper responses
> feat: use albedo as backend server

- regex-assembly/934140.ra
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
> fix(934140): update regex

- tests/docker-compose.yml
- update testing containers to release/20240609.
- change logs to use directories where non-root user from servers can write properly.
- alpha sorted environment vars
- update containers
- reduce permissions
Fixes #3738.
> chore: update testing containers to release/20240609

- CHANGES.md
- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
> chore: create release v4.4.0

- regex-assembly/932175.ra
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932175.yaml
Unix alias bypass with `-p` flag in bash shell.
> fix: alias false negative

- SECURITY.md
- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
* feat: added arithmetic expansion payload by @Xhoenix in https://github.com/coreruleset/coreruleset/pull/3756
* fix(security): alias false negative by @Xhoenix in https://github.com/coreruleset/coreruleset/pull/3740
* feat: add test overrides for nginx by @theseion in https://github.com/coreruleset/coreruleset/pull/3369
* fix: use proper capture for log output of 932300 by @theseion in https://github.com/coreruleset/coreruleset/pull/3763
* chore: use lowercase character class for 932320 by @theseion in https://github.com/coreruleset/coreruleset/pull/3772
* fix: remove nonnecessary variable (932260 PL1) by @dune73 in https://github.com/coreruleset/coreruleset/pull/3773
* @aryehb made their first contribution in …
> chore: release v4.5.0

- .github/workflows/lint.yaml
- regex-assembly/941160.ra
- util/crs-rules-check/rules-check.py
> docs: improve documentationt of 941160

- .github/workflows/test.yml
- tests/docker-compose.yml
> ci: fix docker compose call

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
> test: enable disabled 920480 tests

- SECURITY.md
> fix: update supported versions

- util/crs-rules-check/README.md
- util/crs-rules-check/examples/test13.conf
- util/crs-rules-check/rules-check.py
> feat: check if rule use TX:N target without capture action

- .github/workflows/test.yml
- tests/regression/nginx-overrides.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920260.yaml
- tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933110.yaml
> chore: set up nginx tests

- regex-assembly/942130.ra
- regex-assembly/942131.ra
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
> fix(refactor): 942130 and 942131 regex-assembly

- util/geo-location/README
> chore: remove geo-location

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920420.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
> fix: 9EA-241022 v4

- crs-setup.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920420.yaml
- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
> fix: 9EA-241022 v3

- CONTRIBUTORS.md
- rules/restricted-files.data
Add [fish shell](https://fishshell.com/) files to `restricted-files.data`
> feat: add fish shell files to restricted-files.data

- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/web-shells-php.data
- tests/regression/tests/RESPONSE-955-WEB-SHELLS/955120.yaml
Added support for these web shells:
- Tiny File Manager Shell
- WSO Webshell (2024 release)
- Gecko Web Backdoor
Fixes #3897.
> feat: added support for new web shells

- crs-setup.conf.example
> docs: extended rule documentation (900200)

- .github/workflows/quantitative.yaml
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- Quantitative test is not going to fail even if more false positives are detected
- A comment is added to the PR showing the results of the testing
- Quantitative test is executed only if there are changes under `rules/` folder
> chore: quantitative diff

- .github/workflows/quantitative.yaml
- .github/workflows/test.yml
- update go-ftw release
- add enhancements to quantitative
> chore: update ftw release

- CONTRIBUTORS.md
- reflect reality in the contributors file
- keep file up to date
> chore: update leaders

- tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920221.yaml
Added a test for an empty REQUEST_BASENAME for 920221.
> feat: Add empty REQUEST_BASENAME test for 920221

- .github/release.yml
Plus: cleanup by removing unnecessary labels in release.yaml.
> feat: release yaml support for new label release:remove-rules

- regex-assembly/932300.ra
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- properly apply regex flags
- clean up regular expressions
> fix: make 932300 actually case-insensitive

- crs-setup.conf.example
> fix: issue 3809

- rules/REQUEST-922-MULTIPART-ATTACK.conf
> fix: multipart header tag consistency

- crs-setup.conf.example
- add warning about modifying default charsets
- fixes #4002
> docs: add warning about default charsets modification

- regex-assembly/933160.ra
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/php-function-names-933150.data
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933150.yaml
- tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
> fix: move fopen to 933160 to resolve fp with `RootAndLeafOpenCamera.jpg` (933150 PL-1, 933160 PL-1)

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- regex-assembly file has a clear description of the rule detection target
- update message to match said target
- documentation
- set expectation and clear meaning. previous was ambiguous and rather useless
> fix(941210): update log message to reflect rule javascript word detection

- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934130.yaml
> fix(934130): extend prototype pollution payload

- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml
> feat: added new XSS payloads

- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
> feat: add more default session cookie names

- rules/lfi-os-files.data
- rules/restricted-files.data
- rules/restricted-upload.data
I got these entries from my logs so these files are already being accessed by bots at scale.
> feat: add additional files commonly accessed by bots

- renovate.json
> fix: fix renovate configuration

- rules/lfi-os-files.data
- rules/restricted-files.data
- rules/restricted-upload.data
> feat: block database yaml files

- SECURITY.md
> docs: fix flag in gpg command

- regex-assembly/933160.ra
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/php-function-names-933150.data
> fix: false positives with session tokens/cookies 933150

- rules/RESPONSE-955-WEB-SHELLS.conf
Improve regex with negated pattern matching.
> fix(955xxx): remove dot star

- rules/RESPONSE-950-DATA-LEAKAGES.conf
- fix bad version in rule
- keep version current
> fix(950150): commit bad version

- .pre-commit-config.yaml
- do not run always on every change, only when yaml files in the tests directory are changed
- speed
> fix(pre-commit): do not run every time on all yaml files

- CHANGES.md
- crs-setup.conf.example
- rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
- rules/REQUEST-901-INITIALIZATION.conf
- rules/REQUEST-905-COMMON-EXCEPTIONS.conf
- rules/REQUEST-911-METHOD-ENFORCEMENT.conf
- rules/REQUEST-913-SCANNER-DETECTION.conf
- rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
- rules/REQUEST-921-PROTOCOL-ATTACK.conf
- rules/REQUEST-922-MULTIPART-ATTACK.conf
- rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
- rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
- rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
- rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
- rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
- rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
- rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
- rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
- rules/REQUEST-949-BLOCKING-EVALUATION.conf
- rules/RESPONSE-950-DATA-LEAKAGES.conf
- rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
- rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
- rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
- rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
- rules/RESPONSE-955-WEB-SHELLS.conf
- rules/RESPONSE-956-DATA-LEAKAGES-RUBY.conf
- rules/RESPONSE-959-BLOCKING-EVALUATION.conf
- rules/RESPONSE-980-CORRELATION.conf
- rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
* fix(942340): remove dot star by @Xhoenix in https://github.com/coreruleset/coreruleset/pull/4220
* chore: revert 4206 by @fzipi in https://github.com/coreruleset/coreruleset/pull/4221
**Full Changelog**: https://github.com/coreruleset/coreruleset/compare/v4.17.0...v4.17.1
> chore: release v4.17.1

- .github/workflows/lint.yaml
Fix the failed [action](https://github.com/coreruleset/coreruleset/actions/runs/17354797513/job/49266213684).
> fix: eliminate the effect of backquote character in linter workflow

- rules/sql-errors.data
> fix: duplicate in sql-errors.data
