coreruleset/coreruleset

.github/workflows/test.yml, tests/regression/conftest.py
This one changes the test name in GHA, and changes the default test name for py.test.
=> fix(ci): change test name and fix default params

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921130.yaml
Security researcher Amit Klein found two CRS bypasses. 
The first one is a possible bypass in rule 921130 with not supported HTTP versions, if the server accepts any protocol versions.
This PR enhances rule 921130 so that it also detects not supported HTTP version such as HTTP/3 for example.
=> Prevent bypass of rule 921130

crs-setup.conf.example
Change references for: `RESPONSE-999-EXCEPTIONS.conf.example` 
to: `RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example`
=> Fix filename reference

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920510.yaml
TL;DR some "bad bot" tries to mimic a real browser but with wrong cache-control request header directive and it should be easily blocked with a cache-control directive whitelist rule.
Recently I received two DoS attacks from a widely distributed botnet (more than 5000 unique IPs that made more than 12 million HTTP requests in a few hours):
After the first attack (the green one on the screenshot) I've looked at the requests and I saw that all requests mimic a real browser but come with a wrong Cache-Control request header (`cache-control: private`). The RFC 7234 section 5.2.1 and 5.2.2 (https://tools.ietf.org/html/rfc7234#section-5.2.1) says that "private" is a cache-control directive that a server could send in an HTTP response and not in a request. So I've written a rule to whitelist all …
=> Cache-Control: a strict whitelist of possible values

rules/REQUEST-901-INITIALIZATION.conf
For `SecRule` `msg`, the value is some format string.  It may be
tempting to wrap it across multiple lines, but that does not seem to be
possible as trailing backslashes don't escape newlines.  For instance,
having
```
msg:'Blah blah
blah',\
```
causes the message to appear in logs as
```
Blah blah\x0ablah
```
and having
```
msg:'Blah blah\
blah',\
```
causes the message to appear in logs as
```
Blah blah\\x0ablah
```
Fix all instances of a `msg` value wrapping across newlines: just one in
`REQUEST-901-INITIALIZATION.conf`.
=> fix: change msg values to not span multiple lines

rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942380.yaml
Fixed 3 typos found by fossies Codespell Project in the 3.3/dev branch.
https://fossies.org/linux/test/coreruleset-3.3-dev.3b4a13b.200602.tar.gz/codespell.html
Those typos are also present in the 3.2 branch, however they are only in either comments or regression tests and I don't think we need to backport them. Otherwise let me know.
=> fix typos found by fossies codespell

rules/REQUEST-910-IP-REPUTATION.conf, rules/REQUEST-911-METHOD-ENFORCEMENT.conf, rules/REQUEST-913-SCANNER-DETECTION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf, rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf, rules/RESPONSE-950-DATA-LEAKAGES.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
This is based on the discussions on slack and the blog post at https://coreruleset.org/20200608/overhauling-the-crs-tags/
It is the 1st of 2 PRs. The 2nd PR will add the new CAPEC tags.
=> Drop unneeded tags

rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
Modifying calendar events triggers an XML parsing error (rule 200002 in `modsecurity.conf`) which can be whitelisted in `REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf`.
This is essentially the same as [this issue](https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1742), but for calendar events.
* Click on some calendar event
* Click the "More button" in the dialog
* The event details open to the right of the window
* Modify event details, e.g. location & categories
* Click "Update" at the bottom
This PR disables 200002 with `PUT` requests into `calendars`.
=> Suppress rule 200002 when editing calendar events in Nextcloud

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921120.yaml
This is a PR I copied from the old repo. See https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1746 for history.
This PR solves issue #1615.
The request headers must now be followed by optional space characters and at least one word character.
In reality, other request header values than word chars are allowed, but we don't want to match the whole request header in this rule. We just want to be sure that at least one word char follows the request header. I thought this is enough.
=> Fix FP in 921120 (mv PR from old repo)

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920420.yaml
This is a new attempt and copy of #1807.
This is a copied PR from the old repo: SpiderLabs/owasp-modsecurity-crs#1740
See old PR for a history.
The CRS Content-Type check is case sensitive. But request headers should be case insensitive.
This PR adds t:lowercase to the rule 920420 that compares the sent Content-Type request header with a list of Content-Types defined in an initialization rule 900220.
This PR also adds a regression test for the new allowed Content-Type multipart/related from a already merged PR SpiderLabs/owasp-modsecurity-crs#1721 and a new regression test with a Content-Type starting with an uppercase letter.
=> Make Content-Type case insensitive 920420 (mv PR from old repo)

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
This rule is a more stable and less prone to FPs version of the #1602 
unlike the previous version, this regex tries to match the following techniques:
- uninitialized variables (https://www.secjuice.com/web-application-firewall-waf-evasion/)
- string concatenations (https://medium.com/secjuice/web-application-firewall-waf-evasion-techniques-2-125995f3e7b0)
- globbing patterns (https://medium.com/secjuice/waf-evasion-techniques-718026d693d8)
If you can review the regex, I'll test it on my production
=> 932200: RCE bypass techniques

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921110.yaml
Security researcher Amit Klein found two CRS bypasses. 
The second one is a possible bypass in rule in 921110.
This PR enhances rule 921110:
* `REQUEST_BODY` is also checked, not only `ARGS_NAMES|ARGS|XML:/*`
* The leading CR/LF character is removed
* The regex after `http` is enhanced with `\/\d`
The first two changes may lead to new false positives.
The third change is made to reduce these FP again.
=> Prevent bypass of rule 921110

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Fixes the protocol ossification problems in rule 920510.
For discussion, see the issue #1821.
For more discussion, see the comments on the original feature in #1777.
=> move 920510 to PL3 to address protocol ossification concerns

rules/REQUEST-910-IP-REPUTATION.conf, rules/REQUEST-911-METHOD-ENFORCEMENT.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf, rules/RESPONSE-950-DATA-LEAKAGES.conf
This closes gaps with the CAPEC tagging and I also found rules without the OWASP_CRS tag along the way. Plus a typo in a comment.
=> Fill in missing CAPEC tags and also OWASP_CRS along the way

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Referring to #1818 and from our slack channel
> Ok, I was panicking too much when updated CRS to 3.3.0 RC2 and saw LOTS (I mean really lot) of blocked requests. I had sites which operate normally with argument values like '$randomstring' or 'random$tring' and rule 932200 blocked them. I made specific exceptions and sites are working normally again :) But I would suggest to update it a bit, because every value which contain dollar sign, gets blocked. For example value "pa$sword": https://regex101.com/r/JgZFRi/8 . And this rule needs version updated to OWASP_CRS/3.3.0 (now it's OWASP_CRS/3.2.0). Or this: https://regex101.com/r/JgZFRi/9
this PR adds 2 chains in the rule checking for a whitespace character and a forward slash to complete the match of 932200 regex. This should prevent FPs when …
=> Fix FPs on 932200

CHANGES, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
In #1818, Taiki-San reported large FPs on new rule 932200. In #1820, we tightened the rule to be more specific. I tried out the rule and didn't find any FPs myself, although I'm starting to think my setup uses so many exclusions that I can't effectively test for FPs. So, I'm still feeling a bit scared about enabling the rule in PL1 at this point.
I discussed this with my co-leads, and we decided that it's best to put this rule in PL2 for this release, and move it to PL1 for the next release, based on reports from the field. In this way, professional users can already use the rule, while novice/wholesale users will not have potential trouble. We can gain more experience and see how FP-prone it is in a real life scenario.
I'll create an issue for 3.4 so it isn't forgotten.
=> Move 932200 to PL2

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942230.yaml
This is a copied PR from the old repo. See https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1674 for history.
This PR solves issues #1607 and #1598 and adds new regression tests.
A "having" SQL statement only makes sense in combination with a SELECT statement somewhere.
The whole new regex is:
`(?i:[\s()]case\s*?\(|\)\s*?like\s*?\(|select.*?having\s*?[^\s]+\s*?[^\w\s]|if\s?\([\d\w]\s*?[=<>~])`
The important part is `select.*?having\s*?[^\s]+\s*?[^\w\s]` (original part was `|having\s*?[^\s]+\s*?[^\w\s] only`)
I'm not quite sure about my `.*?` maybe there would be a better option. But we definitely solve the reported false positives. A word boundary with `\b` would not be sufficient.
For info:
We cover the `having` clause in 5 other rules too:
``` …
```
=> Fix FP with sql having in 942230 (mv PR from old repo)

rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942230.yaml
Added new rules to fix the Nextcloud Desktop client sync being blocked as well as the iOS calendar sync (when adding calendar using caldav).
=> Fixed Nextcloud desktop client sync and IOS Calendar sync

rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
People use complex login names, which is acceptable to XenForo but not yet to us.
=> XenForo: exclude login field

rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
The outer rule had t:lowercase already.
=> Remove unneeded transformation from MATCHED_VARS

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941120.yaml
This solves a part of the problem of #1828 by adding a character limit to the regex.
Before:
[a-zA-Z]+
After
[a-zA-Z]{3,25}
Also adding 3 tests.
=>  Eliminate FPs in 941120 by applying character limit to regex

rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
This PR (probably) resolves the FP reported in #1468 by adding a word boundary in front of `pg_`
Old regex: `|Warning.*pg_.*|`
New regex: `|Warning.*\bpg_.*|`
=> Fix FP in Postgres SQL Information Leakage Rule 951240

rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
The site-health.php response could lead to a false positive in the database error rule 951220.
Fixes #1862.
Code was contributed by @Fregf in that issue.
=> WordPress: add exclusion for site-health.php 'SQL server' response

rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
When you open Nextcloud iOS app (v3.0.1) it sends the following request:
```
GET /ocs/v2.php/apps/files_sharing/api/v1/shares?reshares=false&subfiles=false HTTP/2.0
content-type: application/xml
```
Again this triggers rule ID 200002 ("XML parsing error: XML: Failed parsing document.") as there is no body in the `GET` request.
Open the Nextcloud iOS mobile app and you can see the rejected request:
This PR disables 200002 for the aforementioned URL path.
=> Suppress rule 200002 when Nextcloud mobile app accesses shares through API

rules/RESPONSE-980-CORRELATION.conf
Replace the non-existent variable `TX:MONITOR_ANOMALY_SCORE` with the well-used variable `tx.executing_anomaly_score` which, based on their names, is likely the one that was intended to be used.
This solves Issue https://github.com/coreruleset/coreruleset/issues/1897.
=> Fix chained condition for correlation rules 980120 and 980150.

rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
Improvements to the WordPress exclusion profile.
- Fixes #1834 by excluding all rules on the excerpt parameter, and rule 921110, while making/editing a post.
- Fixes #1884 by excluding rule 932200 on wp_http_referer parameters. This parameter appears on many endpoints.
=> Wordpress FP fixes

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
The comment referred to the wrong rule ID.
=> Fix stricter sibling comment for SQL Injection

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
=> Permit "version" string in content-type header, rebased to 3.4 + test, v3

tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941310.yaml
While doing tests for getting a new ftw version using py3, I found that these tests should have had the charset involved to be working properly.
=> fix(test): fixes tests lacking charset

rules/REQUEST-901-INITIALIZATION.conf
Files .axd are used by ASP.NET applications and are intended to be loaded by web browsers. See https://fileinfo.com/extension/axd and issue #1923 .
=> Remove .axd from restricted extensions

rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
Add a WordPress Exclusion Rule
WordPress has a site health page in the admin portal that triggers 2 data leakages errors in the current default rule set up even when using the WordPress exclusion package.
* 951220 - 951-DATA-LEAKAGES-SQL.conf 
* 953110 - 951-DATA-LEAKAGES-PHP.conf
This adds an exclusion rule for the site health page to disable these 2 rules.
This implements #1919
=> WordPress Site Health Exclusion Rule

rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf, rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf, rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf, rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf, rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf, rules/REQUEST-903.9007-PHPBB-EXCLUSION-RULES.conf, rules/REQUEST-910-IP-REPUTATION.conf, rules/REQUEST-911-METHOD-ENFORCEMENT.conf, rules/REQUEST-913-SCANNER-DETECTION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/RESPONSE-950-DATA-LEAKAGES.conf
Decreased the `phase` values where variable activated the previous phase - eg. `REQUEST_FILENAME` available in `phase:1`, not necessary to wait to 2nd phase (body processing). All changes are from `phase:2` to `phase:1`, except in case of rule 950100, which is a response rule - there the old phase value is 4, now it's 3.
=> Decreased the 'phase' values where variable(s) allow(s)

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942160.yaml
This PR fixes issue #1904 by adding REQUEST_BASENAME to rule 942160 at PL1.
I think this is not super dangerous, the rule checks for `(?i:sleep\(\s*?\d*?\s*?\)|benchmark\(.*?\,.*?\))`.
Minimal strings that matches are:
- `sleep()` 
- `benchmark(,)` 
I think this is not super legit.
For further discussion about where to add REQUEST_BASENAME please see issue #1904.
This PR also adds a regression test that tests with the path provided by the original reporter: https://domain/if(now()=sysdate(),sleep(12),0)
=> Fix blind SQLi detection at PL1 Issue 1904

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-949-BLOCKING-EVALUATION.conf, rules/RESPONSE-959-BLOCKING-EVALUATION.conf
This bring a new config item tx.blocking_early that will (when enabled) evaluate anomaly
scores at the end of phase 1 (in addition to phase 2) and at the end of phase 3 (instead of phase 4).
* Enable early blocking in crs-setup.conf
* Set inbound anomaly threshold to 5
* Set PL to 2
* Issue this request: `curl -v -H "Accept:" -H "Host: 1.1.1.1"
http://localhost`
* Rule 949111 should trigger and the request should be blocked.
* Enable early blocking in crs-setup.conf
* Set outbound anomaly threshold to 4
* Set PL to 2
* Enable a proxying on the test machine to a non-existing backend (-> status 502)
* Access the test machine on the path that is being proxied (-> `curl -k https://localhost/proxy/foobar`)
* Rule 959101 should trigger and the request should be blocked
* Please note that there …
=> Introduction of Blocking Early feature

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921110.yaml
This drops pre-HTTP/1.0 support, partially reverting 80d2338.
Should address #1883.
=> Rework pattern to fix false positive

rules/RESPONSE-955-WEB-SHELLS.conf
Adding new type of response body blocking - various web shells. Currently supporting only PHP web shells as i'm not able to host ASP applications (found about 2 ASP web shells). First version is able to block 24 different PHP web shells.
Huge note: This will pevent displaying of web shells only for newbie attackers as it's based on patterns found in response data (which can be changed by modifing the application). Also, gzipping of response data will bypass blocking :( was not able to workaround this. It would be really usefull if modsecurity supports something like 'decompress' transformation function.
**Finally, some help needed: I'm lost with setting of various tags in rules, can anyone help? Current tags are invalid.**
=> New respose body blocking: Web shells

.github/workflows/test.yml, .gitignore, tests/docker-compose.yml, tests/regression/config.ini, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920160.yaml
Some improvements to the test pipeline:
- use relative paths, so when executing local tests would be easy to use
- provides artifacts when the build fails, so you can download the corresponding web server files
- switch to local container instead of using http://www.example.org as backend.
Changing to httpbin.org container has the side effect of returning 405 for one test so the url for the test needs to be fixed.
=> feat(ci): use relative paths in testing

.github/workflows/test.yml
This PR should annotate failed tests in the github interface.
=> feat(ci): add test plugin to annotate failures

rules/RESPONSE-950-DATA-LEAKAGES.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf, rules/RESPONSE-955-WEB-SHELLS.conf
As suggested by @theMiddleBlue, logging whole RESPONSE_BODY isn't a good idea.
=> Removing %{MATCHED_VAR} from logging

.gitignore
This is the first of a series of PRs that decouple #1906 in smaller changes.
Just ignore environment files useful for docker-compose.
=> feat(git): ignore docker-compose environment files in git

rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
- rule 9002401 should skip over the WP rules in phase:2 when exclusions are deactivated by admin (performance)
- add more wp_http_referer FP exclusions
- nav-menus should also be excluded on edit
- add more exclusions to nav-menus
=> WordPress exclusion profile improvements

rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
Real-world example of FP (some of POST arguments):
```
plugin=easy-remove-item-menu/easy-remove-item-menu.php
slug=easy-remove-item-menu
action=update-plugin
```
```
plugin=easy-remove-item-menu/easy-remove-item-menu.php
slug=easy-remove-item-menu
action=delete-plugin
```
=> Fixing FP in WordPress while updating or deleting a plugin

crs-setup.conf.example, rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf
First, not-valid, version of exclusion rules package for phpMyAdmin. I decided to do a pull request because i need to discuss one thing with you.
See these rules:
9008110
9008140
9008230
9008240
There's, currently, no way in modsecurity to use a regexp in variable names within `ctl:ruleRemoveTargetById` (and similar options). How to properly resolve this problem?
=> phpMyAdmin exclusion rules package

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933210.yaml
This PR solves the issue #1950.
=> Avoid FP at rule 933210 when Cookie contains / (slash)

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
`Sec-Fetch-User` is specified [1] as Structure Header boolean [2] and
hence (if present) should only be `?0` or `?1` [2]. Other values are
suspicious. This also agrees with values seen in real-life traffic.
Hence, the broad `@validateByByteRange` was unnecessarily lenient, and
we make the rule more strict.
Fixes #2019
[1] https://www.w3.org/TR/fetch-metadata/#http-headerdef-sec-fetch-user
[2] https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-19#section-3.3.6
=> Request header Sec-Fetch-User: Allow only booleans

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920275.yaml
Rule [920275](https://github.com/coreruleset/coreruleset/blob/b6c548aa9b88a232e6cce975eabd9701cc7644af/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1552) wasn't associated with regression tests. This patch adds some.
=> Added regression tests for 920275

INSTALL
According to modsecurity documentation, `Include` directive used in installation process for Nginx and IIS supports wildcards:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)
```
The include directive also supports wildcard characters (*) and full paths. It should be easy to add something like the following (assuming CRS has been downloaded and installed to this path):
Include /opt/owasp-modsecurity-crs/modsecurity_crs_10_setup.conf
Include /opt/owasp-modsecurity-crs/rules/*.conf
```
Not sure why we are not using it, maybe previous versions of modsecurity doesn't supports this. I also double checked this behavior in modsec source: Wildcards are really supported and matched files are processesd in `ASCII collation order`. Important to note is that i didn't test it.
=> Documentation: Enhancement of installation process for Nginx / IIS

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933210.yaml
This is the first attempt in order to fix 933210 bypass at PL1. In few words:
- all PHP syntaxes matched by 933210 need a `;` at the end of payload to be a valid PHP syntax. I've added it at the end of regex to be more strict on what it matches or not
- added `"`at the first part of the regex to match a function call using string
- added `\` to match function call using string including escape sequences
I think this way we can reduce the number of FPs, what do you think about it?
=> Try to fix 933210 bypass at PL1, lowering FPs

tests/regression/tests/REQUEST-944-APPLICATION-ATTACK-JAVA/944200.yaml
Differences in how py2 and py3 handle bytes require we change this test for it to work properly for both
This is only a draft for the purpose of running it in the pipeline in py2.
=> fix(test): verify that test encoded works in py2 also

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933210.yaml
I thought of a possible evasion in rule 933210 by adding spaces in front of the `;` character.
This is allowed in PHP but was not yet caught by the rule.
=> 933210: check for spaces before ';' character

tests/docker-compose.yml
While doing tests using go-ftw, we found that nginx tests were not logging properly to error.log file.
Setting `LOGLEVEL` solves this.
=> fix(compose): setting LOGLEVEL so nginx logs to error log properly

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930110.yaml
Fixes a false positive reported in #2005.
=> 930110: make bare '..' without (back)slashes not trigger

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920274.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920275.yaml
The `Sec-CH-UA` and `Sec-CH-UA-Mobile` request headers are currently excluded from rule 920274.
`Sec-CH-UA` should not be excluded at all, and `Sec-CH-UA-Mobile` should get validated as Structured Header boolean.
Fixes #2027.
=> Fix Sec-CH-UA and Sec-CH-UA-Mobile request header validation

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml, util/regexp-negativelookbehind/negativelookbehind-920120.data, util/regexp-negativelookbehind/negativelookbehind.py
This PR migrates the PR https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1663 by @allanrbo to our new repo.
There was a lot of discussion in the old PR (see link above). Especially in terms of performance. @fgsch and @dune73 were involved.
Since this PR is an optimization in relation to the regex (negative looks are avoided), I think it makes sense to migrate this PR and pursue it further. And that is only possible if we also have the PR in this new repo.
Next steps would be, as also mentioned in the old PR:
* Testing the rule in prod: performance
* Testing the rule in prod: coverage
=> Migrate PR: RE2 compatibility for 920120

rules/scanners-user-agents.data
Add [`httpx`](https://github.com/projectdiscovery/httpx) detection to scanners-user-agents list.
This is a relatively generic http tool. In practice it is used in conjunction with projectdiscovery/nuclei & subfinder for HTTP server, resource enumeration.
Default user-agent is `httpx - Open-source project (github.com/projectdiscovery/httpx)`:
https://github.com/projectdiscovery/httpx/blob/d7d906150c906a40583a6e9d8812254d50684160/common/httpx/option.go#L47
```
DefaultUserAgent:         "httpx - Open-source project (github.com/projectdiscovery/httpx)",
```
=> add httpx to scanners-user-agents

rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
referring to #1589 this is an example exclusion rule to use in order to exclude specific rules on trusted requests by monitoring tools and script.
=> Example exclusion rule: monitoring agents exceptions

README.md
=> Fixing OWASP Slack URL in readme

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942230.yaml
This PR solves issue #1914 - FP for "case" in Rule 942230.
Like the reporter already mentioned, a pure `case` statement is no valid sql. And he also proposed to extend it with `when then...`
This PR removes the `(` (which is not needed for a case statement) and adds the `when...then...` 
It also adds a test for the reported FP and changes an existing test, that tested on ` case (` only.
=> Fix FP in 942230 with case

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942190.yaml, util/regexp-assemble/regexp-942190.data
This PR fixes issue #2047 (False Positive with "Union von" rule id 942190) by extending the keyword `union`.
`Union` alone does not make sense. But it makes sense when a `distinct`, `all` or `select` follows the `union`.
We already fixed a similar FP in rule 942360 in 2018 in this [commit here](https://github.com/coreruleset/coreruleset/commit/6c5f4550f874f66b4b3d9d0222336cfbf4b26a23#diff-ca2e05f6521d61919bf1d74d07d511cd1ccef6bdf553103cac21c0d757979044R132).
I also fixed some tests. They did no longer match, because I extended the regular expression in the rule. 
And I added a new test, that tests if the reported FP is gone.
=> Fix FP in rule 942190 with keyword UNION

crs-setup.conf.example
Sampling Mode description indicates, you can silence the log by updating 901150 when it's in fact 901450.
It's always a bit troubling when you encounter bugs several years after you released something.
=> Typo in Sampling Mode description pointing to the wrong rule in crs-setup.conf

rules/restricted-files.data
WEB-INF directory is used by Java application to store non-public application data. From the specification:
A special directory exists within the application hierarchy named “WEB-INF”. This directory contains all things related to the application that aren’t in the document root of the application. The WEB-INF node is not part of the public document tree of the application. No file contained in the WEB-INF directory maybe served directly to a client by the container.
This fixes #2089.
=> Adding WEB-INF into restricted-files.data

.github/workflows/stale.yml
Stale issues workflow has been failing since some days ago. Let's upgrade to latest major version to see if they get fixed.
=> fix(ci): try fixing stale issues workflow

rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930120.yaml, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930121.yaml
I'm not sure if i'm approaching this correctly. The target situation is:
- do not block Google OAuth2 callback requests (we need to whitelist it)
- make sure that GOAuth2 whitelist won't open new holes in the firewall
This would be an easy task if 'logical OR' was available in SecRule or in chaining of multiple SecRules (i don't know of any at least similar functionality in modsecurity).
I decided to create a detection rule (930050) for Google OAuth2 callback, which is as tight as possible to not allow any bypass or data injection. Finally, i chained rule 930120 (which was triggering with Google OAuth2 callback) with new one which checks if Google OAuth2 callback request was detected.
=> Fix for issue #1922

.github/workflows/lint.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920100.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920160.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920181.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920240.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920280.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920400.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920420.yaml, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921140.yaml, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941110.yaml, tests/regression/tests/REQUEST-944-APPLICATION-ATTACK-JAVA/944120.yaml, tests/regression/tests/REQUEST-944-APPLICATION-ATTACK-JAVA/944210.yaml
We admitted tests using list of stings and others in `ftw`. For compatibility, we should use only valid yaml in our tests.
This one fixes this.
=> fix(tests): use only valid yaml in tests

rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
This PR adds a note to the commented rule [9003610](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf#L30-L35), namely `ctl:requestBodyLimit` action is not supported in libmodsecurity3.
(Of course) this won't solve the #2069, but we can notify the users about the engine limitation.
I have reviewed all commented `SecRule` in whole rule set, and didn't find any other malfunctioning.
=> Added a note to a commented rule about unsupported action in v3

rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
OwnCloud 10.6.0 use `/remote.php/dav/` to upload (PUT) file instead of `/remote.php/webdav/` that raise FP caused by rule id [9003001](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf#L68) is not match as expected.
The confusion between `dav` and `webdav` already discussed on Owncloud official doc [Issue#23762](https://github.com/owncloud/core/issues/23762).
closes #2126
=> Owncloud: Fix rule 9003001 to match both dav and webdav

CONTRIBUTING.md, crs-setup.conf.example, rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example, rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf, rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf, rules/REQUEST-910-IP-REPUTATION.conf, rules/REQUEST-913-SCANNER-DETECTION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913100.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920510.yaml, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930120.yaml, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941181.yaml, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941190.yaml
PR for issue #2083 : Replace blacklist and whitelist with deny list and allow list.
Rule and Test comments, descriptions and alert messages have been updated to replace blacklist and whitelist with deny list and allow list respectively.
NOT modified, to preserve history (as per slack meeting discussion)
NOT updated parameter names: MODSEC_PROXY_BLACKLIST and MODSEC_PROXY_WHITELIST
Project Honey Pot HTTP Blacklist, updated to abbreviation "HTTP:BL" in keeping with projects current naming and usage on project and FAQ pages.
Updated description to use deny list but not argument name as that would break rule, assuming wordpress has not updated ARG name.
`ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:blacklist_keys`
rule 910110 references filename ip_blastlist.data. Has not been changed
After slack …
=> Replace Blacklist and Whitelist with Deny list and Allow list

tests/regression/CRS_Tests.py
As NGINX doesn't give us microsecond level by detail, ftw_start was already rounded down in code but ftw_end was not which was failing the testcases in the suite.
=> Fixed the logging problem for nginx

tests/regression/README.md
The default parameter for logs in conftest.py is modsec2-apache, which causes ModSecurity to always look for [modsec2-apache] in config.ini.This causes problem with nginx server as its logging regex are different.This is solved by changing default parameter from modsec2-apache to modsec3-nginx in conftest.py
=> Updated README.md for nginx

rules/REQUEST-910-IP-REPUTATION.conf
Remove old rule 910110 which has been commented out a long time.
Spider labs web honeypots thought to be no longer running.
=> Remove Rule 910110

rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-905-COMMON-EXCEPTIONS.conf
As at least some of our users are using multiple rulesets togather (for example one of our sponzors, Kemp Technologies), we should try to not collide with other rulesets - in this case, do not turn off the whole ModSecurity but only CRS instead.
Btw, is `ctl:ruleRemoveByTag` really unsupported by ModSec3 or it's only outdated documentation?
=> Replace usage of ctl:ruleEngine=Off by ctl:ruleRemoveByTag=OWASP_CRS

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930110.yaml
This commit amends the regular expression for rule 930110.
The previous representation of the backslash character is replaced with
one which is portable between both Apache and nginx/libmodsecurity.
This commit should resolve the false negative reported in issue #2140
=> Amend the regular expression for rule 930110

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
Looks like [eda83298](https://github.com/coreruleset/coreruleset/commit/eda83298c04a4d0d288e7bf57a12467b44a05d4c#diff-6acdf1bc11f3ddaed59cf74b841c45047e63a9515015f2d1d096a01210ddd027) commit misses two `"` from the end of actions list in rule 930050 [here](https://github.com/coreruleset/coreruleset/commit/eda83298c04a4d0d288e7bf57a12467b44a05d4c#diff-6acdf1bc11f3ddaed59cf74b841c45047e63a9515015f2d1d096a01210ddd027R38) and [here](https://github.com/coreruleset/coreruleset/commit/eda83298c04a4d0d288e7bf57a12467b44a05d4c#diff-6acdf1bc11f3ddaed59cf74b841c45047e63a9515015f2d1d096a01210ddd027R49). This PR fixes it.
I'm wondering why mod_security2 allows it...
=> Added missing " from the end of actions list

tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942500.yaml
Hi CRS team. Thanks for the great product!
Here is a pull request to fix broken tests on Nginx. Let me know if it's better to open an issue first.
The regression test cases, 933160-21 and 942500-1, are failing on Nginx.
The `uri` parameters in tests cases `933160-21` and `942500-1` start with `?param=` without the actual path such as `/`. This is an ill-formed path in terms of the HTTP protocol spec, because it lacks the absoluteURI, abs_path nor authority. ([Link to the spec fyi](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.2).) 
Thus, the generated requests are rejected by Nginx before WAF sees them, which is not an expected behavior.  
JFYI, this happens on Envoy server as well.
Before my fix, Nginx rejects the requests by the test cases with the following log.
``` …
```
=> Fix 933160-21 and 942500-1 tests broken due to invalid URIs

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941130.yaml, util/regexp-assemble/regexp-941130.data
Get rid of a false positive on string `7XMLNS` by adding word boundaries to our regexps in rule 941130.
This is a quicky so let's see what the tests say.
=> eradicate XMLNS FP in rule 941130

rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf
- fixed 2 real-world FPs
- fixed `ruleRemoveTargetById` ordering in rule 9008110 (based on removed IDs)
- adding new rule (was triggering for example for `information_schema` DB)
=> Fixing phpMyAdmin FPs

rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
This PR resolves issue #2139 by moving the ctl action inside a chained rule from the 1st rule (chain starter rule) to the 2nd rule.
This solution was confirmed by the report of the issue.
Also see: 
> In a chain starter rule, disruptive actions are processed when the chain matches, but non-disruptive actions are processed when the rule matches.
in https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/three-modsecurity-rule-language-annoyances/
=> Move ctl action in chained rule to 2nd rule

tests/docker-compose.yml
Turns out we were using the old version. We fell in our own trap.
=> feat(ci): use latest crs containers for testing

.github/workflows/nightly.yml
After merging this one we will have nightly pre-releases with latest CRS code.
Fixes #2034.
=> feat(nightly): add nightly latest releases

.github/workflows/nightly.yml
Our new nightly releases are not updating the tag shown (but the zip file is properly generated). Using a previous step removing the tag is the recommended action.
=> fix(ci): remove tag before releasing

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932170.yaml
This PR adds one positive testcase for Shellshock rule 932170.
=> Add 1 pos testcase for 932170

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920341.yaml
Add positive and negative tests for 920341, POST request body are required to have content-type if content-length != 0
- Standard POST request with length 4 and no content-type
- Standard POST request with length and content-type
- Standard GET request (negative test)
=> test: add tests for 920341

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920300.yaml
After some research*, it seems that HTTP `CONNECT` requests typically do not include an Accept request header.
A user with a web application making use of the `CONNECT` method would find that (at PL 3) rule 920300 causes false positives. This is because rule 920300 expects all requests to feature an Accept header (with the exception of `OPTIONS` requests and requests with a `User-Agent` of either "AppleWebKit" or "Android").
**This PR:**
- adds the `CONNECT` method as an additional exemption, next to the `OPTIONS` method which is already exempt;
- adds three new tests:
- one covering the newly exempt `CONNECT` method;
- one covering the exempt `OPTIONS` method;
- and one covering an exempt `User-Agent` containing the string "AppleWebKit".
---
1. RFC 7231 [provides examples of `CONNECT` …
=> Amend 920300 to exclude CONNECT requests

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, util/regexp-assemble/data/930100-dots.data, util/regexp-assemble/data/930100-slashes.data
This PR disassembles the regular expression from rule 930100, which resolves #2221 _(Disassemble regex in 930100: The regex in 930100 is rather hard to read.)_.
Updated instructions are provided in the rule comments describing how to build the newly disassembled regular expression.
=> Disassemble 930100 regex

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920100.yaml, util/regexp-assemble/data/920100.data
This PR addresses the deficiency with covering the `CONNECT` method, as raised in issue #2220.
**In summary**: an HTTP `CONNECT` request typically includes a domain on the request line. Rule 920100, for some reason, was written to only accept `CONNECT` requests featuring an IPv4 address on the request line.
**This PR:**
- disassembles the regular expression for rule 920100;
- adds support for `CONNECT` requests featuring a domain;
- modifies an existing test for the `CONNECT` method which was previously a false positive (the test uses a domain, and is no longer a false positive).
---
=> Rework and expand 920100

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920171.yaml
This PR also covers the rule 920171 as #2265, but has 2 positive tests (with explicit match) instead of expecting an error.
=> Add test cases (1 neg, 2 pos) for rule 920171

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930110.yaml
This PR resolves issue #2205, a false negative with triple dot (/.../), by extending the current regex with a `\.{2,3}` instead of only `\.\.`.
This PR also adds a positive testcase.
=> Resolve triple dot false negative in rule 930110

rules/RESPONSE-955-WEB-SHELLS.conf
Regex for WSO shell is doing lots of noise such as this:
`Execution error - PCRE limits exceeded`
Fixed by making it anchored.
=> Web shells: Simplifying one of regexes

rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/sql-errors.data
See comments here: https://github.com/coreruleset/coreruleset/issues/2150
I decided to not use regex suggest by @lifeforms (`(?:pg_query|PostgreSQL).{1-20}ERROR`) but this one instead `PostgreSQL.{1,20}ERROR` as error messages containing `pg_query` are catched with another regex (`Warning.*\bpg_.*`).
=> Fixing FPs for PostgreSQL error messages

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
- change `having` to `\bhaving\b` to remove FP
- add test
Fixes #2229
=> fix(sql): update rule to remove false positive

rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
The WordPress plugin "All in One SEO" (https://wordpress.org/plugins/all-in-one-seo-pack/) does some calls which are currently blocked. This exclusion should resolve it.
It's an interesting precedent because it's the first time we moved from WordPress Core to plugins. The future and our users will hopefully tell which other plugins we will need to support in the future.
This resolves #2095.
=> WordPress: add exclusion for aioseo plugin

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Rules 932180 and 932200 are catching RCE attacks but are adding score to LFI - this PR fixes it.
Fixes #2225.
=> Fixing attack type of few rules

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
This PR moves rule 932200 to use \x5c backslash representation and adds two tests for it.
=> Backslashes 932200

rules/restricted-files.data
Exploited in the wild, see CVE-2018-13379 .
`GET /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession`
=> Adding sslvpn_websession into restricted files

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941170.yaml
This PR moves rule 941170 to use \x5c backslash representation and adds two tests for it.
As a bonus, the two existing tests for rule 941170 get Accept headers added (so that they no longer trigger rule 920300, "Request Missing an Accept Header").
=> Backslashes 941170

rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
fix old url link from https://blog.spiderlab.com
to https://www.trustwave.com/
=> REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example: fix old url link

.github/workflows/test.yml, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953120.yaml
Remove pcre2 only syntax.
Fixes #2354
=> re2: use compatible syntax in rule 953120

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932180.yaml
Looks like the test case [932180-2](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932180.yaml#L51) has an invalid end boundary - this PR fixes it.
=> Fixed end boundary string at the test body

rules/REQUEST-903.9008-PHPMYADMIN-EXCLUSION-RULES.conf
Fixing FP in phpMyAdmin exclusions. Adding exclusion for whole `ARGS` as affected fields looks like this:
```
ARGS:fields_prev[multi_edit][0][2063c1608d6e0baf80249c42e2be5804]
ARGS:fields[multi_edit][0][2063c1608d6e0baf80249c42e2be5804]
```
=> Another PMA FP

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920520.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920521.yaml, util/regexp-assemble/data/920521.data
This PR adds two new rules that checks for valid Accept-Encoding request headers.
- Rule 920520 at PL1 only checks for length not greater than 50 characters.
- Rule 920521 at PL3 checks for valid known Accept-Encoding headers.
The PR also adds tests.
We first wanted to check for length in PL3 rule as well, but I think this does not make sense because we already check in rule 920520 at PL1.
Only rule at PL1 920520 blocks CVE-2022-21907. Rule 920521 does not, because `*` is allowed inside the header.
Sources: 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
https://www.iana.org/assignments/http-parameters/http-parameters.xml#http-parameters-1
https://github.com/antx-code/CVE-2022-21907
Feedback welcome.
=> Add new rules 920520 and 920521 to check for valid accept-encoding

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
This PR removes the `\\\\` backslash representation from the regular expression in rule 941330.
This rule will now also work correctly in Nginx, which it didn't before (due to the `\\\\` issue with Nginx), and the tests for this rule work correctly against the Nginx CRS container.
**Note:** The backslash pattern is already covered by test 941330-1, hence a new test is not required in this instance.
This is part of ongoing issue #2332.
If someone could double-check the amendments to the regex, and maybe test that the modified rule catches the payloads expected?
=> Backslashes 941330

.editorconfig
Adds editorconfig file to keep files with correct newline/whitespace.
See https://editorconfig.org/.
=> docs: add editorconfig file to keep spacing in good shape

rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf, tests/regression/tests/RESPONSE-954-DATA-LEAKAGES-IIS/954100.yaml
This PR moves rule 954100 to use the \x5c representation of the backslash character.
A new test is added for rule 954100. It sends a Base64 encoded payload (QzpcaW5ldHB1YiAK) which is `C:\inetpub `. This string is then returned in the response body, causing rule 954100 to match.
=> Backslashes 954100

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
This PR moves rule 920460 to use the \x5c representation of the backslash character.
**Note:** The backslash patterns are already covered by tests 920460-1 to 920460-6, so no new tests are being submitted here.
=> Backslashes 920460

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
This PR moves rule 930110 to use the \x5c representation of the backslash character.
**Note:** Backslash patterns are already tested by 930110-1 and 930110-8, so no new tests are being submitted here.
=> Backslashes 930110

rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf, tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934130.yaml, tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934131.yaml, tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934140.yaml
Prototype pollution is a way to create malicious Javascript objects, for instance by setting their special property `__proto__` or `prototype`. It can lead to RCE, SQL injection and more. These rules detect the server-based attacks (DOM-based attacks after the hash are not seen by the WAF). Some variants are covered and I attempted to prevent bypasses.
Rules added:
- 934130 (PL1) finds `__proto__`, `constructor.prototype`, `constructor[prototype]`
- 934131 (PL2) finds `[constructor]`
Inspiration for payloads came from: https://github.com/BlackFan/client-side-prototype-pollution/blob/master/README.md
Example vulnerable library: TypeORM https://www.cvedetails.com/cve/CVE-2020-8158
I closed my former PR as I messed it up in Git.
=> Detect prototype pollution

rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
- Add support for admin functions: mass send messages and donations feature
- Fix various false positives
- In rule 9006901, fix a phase:1 in a skip that should be a phase:2, so that both phases skip over the admin.php rules.
=> XenForo: add more exclusions to fix FP's and fix phase

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932300.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932301.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932310.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932311.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932320.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932321.yaml, util/regexp-assemble/data/932300.data, util/regexp-assemble/data/932301.data, util/regexp-assemble/data/932310.data, util/regexp-assemble/data/932311.data, util/regexp-assemble/data/932320.data, util/regexp-assemble/data/932321.data
These are two new rules for dealing with email related protocol remote commands (smtp/pop3/imap4).
- New rule 932300 tries to capture base commands that are different enough from common English words to prevent FP
- New rule 932310 is a stricter sibling in PL3 with all the remaining commands
Still to be defined to be considered for merging:
- the prefix/suffix for matching commands
- tests!
=> Email ruleset

.pre-commit-config.yaml, CONTRIBUTING.md
Now that we cleaned whitespace, let's add the pre-commit file so this won't happen again.
Probably we can add some of our tools so we don't waste CI cycles with linting problems.
=> dev: add pre-commit config file

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941190.yaml
This PR moves rule 941190 to use the \x5c representation of the backslash character.
Two new tests are added to ensure that the backslash matches are working correctly.
=> Backslashes 941190

rules/lfi-os-files.data, rules/restricted-files.data
Actively accessed in the wild. For more info, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
=> Adding AWS cli files into restricted

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
This PR updates the comments for rules 932100 and 932110 to use the \x5c representation of the backslash character.
=> Backslashes 932100, 932110

.gitmodules
The PR #2260 got merged without counting anonymous git clones in; as ssh clones only work with an authenticated GitHub account.
This commit changes the git protocol of the documentation submodule from ssh to https.
=> Change documentation git module link to https

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930110.yaml
This PR is a proposal to solve issue #2446 by adding FILES to path traversal detection rules 930100 and 930110.
This PR also adds a test for rule 930110.
=> Add path traversal detection in file upload

rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf, tests/regression/tests/REQUEST-944-APPLICATION-ATTACK-JAVA/944140.yaml
This is a Java version of rule 933110 (blocked uploading .php files), that blocks uploading of .jsp and .jspx files, which may be leveraged to achieve RCE.
=> 944140: deny uploading .jsp and .jspx files

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942440.yaml
often happens that a JWT has a "--something" string inside it. This triggers 942440 because "SQL Comment Syntax" that prevents something like `1+OR+1=1--comment`. An example of false positive:
```shell
curl -s -H 'x-format-output: txt-matched-rules' -H 'x-crs-paranoia-level: 2' "https://sandbox.coreruleset.org/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMe--KKF2QT4fwpMeJf36POk6yJV_adQssw-5c"
```
With this PR I'm trying to add a chained rule that adds this condition:
match only if one of the listed variables don't match `^ey[A-Z-a-z0-9-_]+[.]ey[A-Z-a-z0-9-_]+[.][A-Z-a-z0-9-_]+$`
the regex should match all JWT token format assuming that `{"` should always be b64 encoded  to "ey..."
Do you see problems with …
=> Remove FP on 942440 (JWT)

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
In #2438 a FP was reported on `Content-Type: application/*+json`.
It may be rare but it is allowed according to the RFCs.
The `*` character is added to the allowed characters.
=> 920470: allow * in Content-Type to fix 'application/*+json' FP

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942130.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942131.yaml, util/regexp-assemble/data/942130.data, util/regexp-assemble/data/942131.data
This is an implementation for the idea described in #2353.
These is a summary of the changes:
- splitted rule rule into chain
- set the first match to transaction variable
- checks in the chained rule using regex
- commented the meaning of 942130 data
⚠️ There was a change in the regexp, in particular, inequalities. It doesn't need to be different to obtain a logical output from the query.
=> Re2 support 942130

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, util/regexp-assemble/data/932311.data
After doing a pass for re2 compat we found that this regexp was failing with `error parsing regexp: invalid repeat count: "{0,100}"`.
After reviewing it, I don't think we need to be that precise in this match, for STORE there might be additional flags, but it suffice to match one or not.
Also updated the prefix to be a `[ ]` space instead of an escaped one, because editors might get confused and rip it off because is is a space a the end.
=> fix(932311): remove double m,n in regexp

rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, util/regexp-assemble/regexp-assemble.py
@airween You were right of course, that comment needs to use the new command format.
=> Updated one missed regexp-assemble.py rule comment

util/regexp-assemble/lib/operators/assembler.py, util/regexp-assemble/lib/processors/cmdline.py
@lifeforms Sorry, this is urgent and needs to go into v4.
=> Use type hints in a way that are compatible with Python 3.7+

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, rules/RESPONSE-980-CORRELATION.conf, tests/regression/tests/RESPONSE-980-CORRELATION/980170.yaml
This PR will address the additional issues and comments raised in #2482.
Could we express the operator as `@ge 2` like the comment describes? The negation twists my brain.
Dito. `@eq 0` would be easier. Here the comment is also twisted.
I think it would be useful to add a comment in front of this marker to describe how Reporting-Level 1 and requests with positive score land here.
Why do you put the scores in brackets?
-> `Anomaly Scores: (Inbound Scores: blocking=10, detection=15, per_pl=10-0-0-5, threshold=1) - (Outbound Scores: blocking=0, detection=0, per_pl=0-0-0-0, threshold=10) - (SQLI=0, XSS=0, RFI=0, LFI=5, RCE=5, PHPI=0, HTTP=0, SESS=0)`
Is there a need for a reporting level between the current 1 and 2? This blocking score not yet at threshold, but detection score is already …
=> Reporting rules tweaks

rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, util/regexp-assemble/data/951230.data
FP is doing this pattern:
`Warning.*mysql_.*`
I'm not sure what error message is this supposed to match but while trying to google it, i found only PHP error messages (see below), so i assume it's for PHP errors.
To lower FPs, i made pattern more tighter:
`Warning.{1,10}mysql_[a-z_()]{0,26}`
For the first part of the pattern (`Warning.{1,10}`), i saw multiple versions of the error message:
```
Warninig: mysql_...
Warninig:mysql_...
Warninig : mysql_...
Warninig:   mysql_...
```
For the second part (`mysql_[a-z_()]{0,26}`), i assume we are trying to catch a function name (list: https://www.php.net/manual/en/ref.mysql.php ) and longest function name (`mysql_real_escape_string`) has 24 characters (+2 for brackets). Limiting length of matched data will also create nicer error messages. …
=> Fix FP in MySQL data leakage

CONTRIBUTING.md
PR brings the CONTRIBUTING.MD document in line with the updated, HTML-formatted contribution guidelines from the `/docs` site. Also adds a hyperlink to said HTML content.
=> New contributing.md

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Fix for rule 920470, Modified rule regex to allow Content-Type of the pattern `text/calendar; charset=utf-8; component=vevent`
=> Fix false positive, issue number #2434

crs-setup.conf.example
For those converting their crs-setup.conf to v4, add a note about the disappearance of exclusion packages in favor of plugins.
=> crs-setup.conf.example: add a note for those missing exclusion packages

util/regexp-assemble/regexp-assemble.py
Running the script with './' prefix produces a relative path, which the parser did not handle properly
=> fix(regexp-assemble): Fix parsing of relative paths

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Several rules in 932 were missing the @rx operator (or any operator
fof that matter).
@lifeforms This needs to go into 4.0.
=> fix(rules): Add missing @rx operators to 932 rules

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Same PR as #2536 but to the `v4.1/dev` branch
=> Add missing @rx operators to 932 rules, in v4.1/dev branch

util/regexp-assemble/lib/context.py, util/regexp-assemble/lib/operators/assembler.py, util/regexp-assemble/lib/operators/parser.py, util/regexp-assemble/regexp-assemble.py
* Properly pass and handle the argparse namespace.
* Improve informational and error output
* Don't cache assembler to prevent mixing state
* Fix false warning when updating chain rule where the starter rule
does not use @rx
=> fix(regexp-assemble): Fix some remaining issues

CONTRIBUTING.md
Fixes issues arising from the v4.1 -> v4.0 move and brings CONTRIBUTING.MD in line with the documentation site.
=> Bring CONTRIBUTING.MD in line with documentation

util/regexp-assemble/README.md
Cleans up the syntax of and changes nesting in README to allow for
tools like ronn (https://github.com/rtomayko/ronn) to generate man page
formatting. That way, @RedXanadu can view the README in the terminal ;)
=> chore(regexp-assemble): make README man page compatible

rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
This pull request addresses the bug described in https://github.com/coreruleset/coreruleset/issues/2530 by moving the `ctl:auditLogParts=+E` to the chained rules where there are chained rules.
=> fix(logging): move audit log part E if there is a chained rule

rules/lfi-os-files.data
This is a report from the BugBounty event.
Report id: `4863ZMLJ`
Payload:
```
POST / HTTP/1.1
Host: sandbox.coreruleset.org
User-Agent: curl/7.68.0
Accept: */*
x-crs-paranoia-level: 3
x-format-output: txt-matched-rules
x-backend: apache
x-crs-version: nightly
Content-Length: 23
Content-Type: application/x-www-form-urlencoded
cat /root/.ssh/id_ecdsa
```
=> 930120: Added ECDSA type SSH identity files

util/regexp-assemble/lib/processors/assemble.py, util/regexp-assemble/tests/preprocessor_test.py
Make it possible to mix concatenation and alternation to produce output
that can be stored for later use
=> fix(regexp-assemble): fix complex concatenation

rules/restricted-files.data
Just like the `package.json` & `package-lock.json` already on the restricted files list, the [`npm-shrinkwrap.json`](https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json) (publishable version of `package-lock.json`) also reveals the dependencies as well as the locked versions that are installed. It is _publishable_ in the scope of a web application package, but should not be published with an installed web application.
=> Add npm-shrinkwrap.json to restricted-files

.yamllint.yml
After merging PRs from BB program, we have some long text for tests in 942521. We need to ignore them.
=> fix(lint): remove long lines check for 942521

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942340.yaml, util/regexp-assemble/data/942340.data
This PR contains new regular expressions for different kinds of auth bypasses. In an ideal world, these would be inside the operator dataset, but unfortunately, they look too much like normal sentences to accurately block.
Edit:
* Contains fixes to bypasses found by me (`DV2UKLP4`, `2AUWUOVF`, `RICGZH4Q`)
* Contains fixes to bypasses found by @wfinn (`YPWZU6PD` and `Q6FBUFOD`)
=> fix(sqli): additional regular expressions for SQL auth bypass

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941390.yaml
This PR resolves BB finding 4A9UJH6G (issue #2661) by adding the missing js method `setTimeout()` by addind a new rule.
I also added the problematic methods `setInterval()` and `eval()` and the constructor `new Function()`, because I found them in the same context while researching the topic. 
2 open points to discuss:
* I'm not sure with `eval()` because it's already covered in 934100 and 933160. Do we need this in this new rule 941390?
* I added the new rule to PL1 which is maybe at too low PL. Maybe a higher PL would fit better?
And of course I added tests as well!
=> feat(xss): add js methods to prevent xss

crs-setup.conf.example, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942151.yaml
Relates to **1DQC0CU3**
Associated issue: #2713 
---
PR adds a test to rule 942151 for the SQLite function sqlite_compileoption_used
Adding this test proves that the issue reported in 1DQC0CU3 is now covered and complete.
=> Add new sqlite test

.github/workflows/go-ftw.yml, tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934120.yaml
- fixes yaml syntax in test (using old string list from python's ftw)
- run ftw check before running tests
=> fix(test): fix test using old syntax and add go-ftw check

rules/php-errors.data
This PR will update the PHP errors list. I've added the description to the procedure I'm following to get, with some caveats, all the errors that might be disclosing information.
After doing a pass and documenting the procedure, there is still a manual job based on the experience of the person looking at the lines and removing the nonsense. We might come up with something better, automated, somehow.
Please take a look at the initial comment and let's iterate over the text we can use as errors.
Fixes #2652
=> feat(list): update php errors list

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942130.yaml, util/regexp-assemble/data/942130.data
This PR resolves BB issue #2709 by adding `glob` to PL2 sql tautologies rule 942130.
See linked issue and https://www.tutorialspoint.com/sqlite/sqlite_glob_clause.htm.
=> fix(942130): add glob to sql tautologies

util/regexp-assemble/lib/context.py, util/regexp-assemble/lib/operators/parser.py
Fixes bad selection of files on case-sensitive filesystems.
Thanks for pointing this out @RedXanadu, @airween.
=> fix (regexp-assemble): filter and sort files properly

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933200.yaml, util/regexp-assemble/data/933200.data
Associated issue: #2724
This PR adds the additional PHP wrappers documented at https://www.php.net/manual/en/wrappers.ssh2.php and a new test for each new wrapper:
- `ssh2.shell://`
- `ssh2.exec://`
- `ssh2.tunnel://`
- `ssh2.sftp://`
- `ssh2.scp://`
=> Add more php wrappers

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933211.yaml
Rule 933210 is incapable of blocking `(sy.(st).em)(@id)` when it is passed to the following PHP snippet:
```php
<?php
eval("(".$_GET["rce"].");");
?>
```
This is because the trailing semi-colon is not injected by the attacker, but hardcoded by the receiving application. It's safe to assume that any application that knowingly passes user-input to `eval` does something like this. 
933210 probably does not block this due to the false positives that can come with it, which isn't allowed at PL1. That is why I created a stricter sibling (933211) that evaluates from PL3 and up to take this scenario into account. However, since the trailing semi-colon is now optional (only when at the end of the string), it also matches the following harmless sentence that 933210 avoids:
```
this is a 'dog' (not …
```
=> fix(rce): block PHP function calls without trailing semi-colon (stricter sibling)

crs-setup.conf.example
Relates to **JW2SU88A**
Associated issue: #2757
---
This PR:
- Adds a note about how and why `.axd` was removed from the list of restricted file extensions
- Adds comments providing a list of _optionally_ block-able common archive file extensions
=> Add archive extensions comment

rules/REQUEST-901-INITIALIZATION.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
Variable `TX:sql_error_match` is used to skip rules in file `RESPONSE-951-DATA-LEAKAGES-SQL.conf`. The proper solution for skipping rules should be to use `skipAfter` action, as this PR propose.
Advantages:
- simplifying rules
- make rules compatible with `SecRuleUpdateTargetById` (it doesn't support chained rules)
- more readable exclusion rules as they will exclude `RESPONSE_BODY` directly instead of `TX:sql_error_match`
Disadvantages:
- exclusion rules are not backward compatible (but can be made compatible with both versions at the same time)
=> Removing usage of TX:sql_error_match

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921230.yaml
This fixes bug bounty finding M4IXRHRZ, an exploit that abuses the HTTP request Range header.
Range header seems to have fallen out of fashion. Chrome and Firefox no longer use it on PDFs it seems
and youtube does not use it either anymore. By denying it for PL3, we deny it for high security setups
and if they need it, they can write a rule exclusion for a a specific URI.
We could play around with minimal ranges etc. at PL2 to mitigate this, but this would be very complicated and it is not sure if not a hacker would still find a way around it. 
Also: This is only an exploit that allows you to extract a response that would otherwise be blocked. For it to
work, there has to be a weakness on the backend. So it's a combination of multiple weaknesses and we do not necessarily need to address …
=> Forbid range header at PL3

util/regexp-assemble/lib/processors/cmdline.py, util/regexp-assemble/tests/preprocessor_test.py
The tilde (`~`) symbol can now be used instead of the at (`@`) symbol in
the commandline processor to specify that a word must be followed by the
same tokens as with `@`, except for white space. This makes it possible
to put common english words into word lists, like `python~`. `python@`
would create too many false positives, as `python ` would match.
See discussion in #2677.
=> feat (regexp-assemble): Add alternate suffix evasion pattern

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920420.yaml
As we decided during the last meeting, this PR removes all previous allowed-by-default content-types that can't be parsed by any body-processor. The idea here is to warn the user about allowing content-type like "text/plain" and give a bit of advice on how to allow it on specific paths using a SecRule.
Any review is welcome, also for the comment wording.
=> Remove some default content-type

util/crs-rules-check/README.md, util/crs-rules-check/requirements.txt, util/find-rules-without-test/requirements.txt
The new version is necessary for the newer ruleset.
=> fix(util) Corrected the version number of the Python library

util/regexp-assemble/lib/regexp-assemble.pl
- escape double quotes in prefixes and suffixes
Fixes #2756.
=> fix(regexp-assemble): escape double quoting

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921422.yaml, util/regexp-assemble/data/921422.data
Added `\b` to groups of 921422's regex.
Also added a negative test based on reported issue.
This PR fixes #2783.
=> fix(921422) Added \b to groups to avoid unwanted FP's

CHANGES.md, crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf
=> chore: remove user-agentt from restricted headers

util/regexp-assemble/lib/processors/cmdline.py, util/regexp-assemble/tests/preprocessor_test.py
The tilde flag of the cmdline processor will now correctly match `python<<<foo` and also `python2 foo`. It will not match `python foo`.
=> fix(regexp-assemble): tilde flag also matches extended commands

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf
A merge error occurred during backporting. This fixes the paranoia level skips in 3.2.
=> fix paranoia level skips 3.2

.github/workflows/go-ftw.yml, .github/workflows/test.yml
There are failures sometimes when containers start because we mess with variables or files that might affect modsec when starting. This PR should at least show logs of the start process so we can see the errors in the CI logs.
=> feat(ci): show logs from containers startup

rules/REQUEST-901-INITIALIZATION.conf
I'm working on some new features for `util/crs-rules-check/rules-check.py` script. Before I push them, we need to fix some errors.
This fix sets up the missing default value of a TX variable. There is no other case like this, all other TX variable has default value.
=> Set default value of crs_validate_utf8_encoding TX variable

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
PR resolves #2657 by removing all unnecessary escapes of forward slashes in regular expression patterns (excludes compiled/optimised patterns, which may still escape forward slashes).
Only one instance of an unnecessary escape was found.
=> Remove unnecessary escaping

rules/REQUEST-901-INITIALIZATION.conf
Most of the rules in `REQUEST-901-INITIALIZATION.conf` feature a reference back to the corresponding rule in `crs-setup.conf`.
This PR makes all of these backreferences consistent and corrects a handful of the rule IDs.
Associated issue: #2814.
=> Make rule backreferences consistent and correct

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932175.yaml, util/regexp-assemble/data/932175.data
Add new rule to include `alias` builtin detection.
Fixes #2670.
=> fix(0FA9HCGT): rce alias builtin detection

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932210.yaml, util/regexp-assemble/data/932210.data
This PR resolves BB finding N9FKP2XQ in issue #2735 by adding `sh`, instead of only `shell`, to rule 932210.
And this PR also adds the BB test string.
=> fix(sqli): add finding N9FKP2XQ

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml, util/regexp-assemble/data/942120.data
Adds two additional SQLi words.
Fixes #2732 and #2733.
=> fix(sqli): add HOH7M88Q-IJ5N1CXB findings

.github/workflows/test.yml
We don't need to know which tests passed, we only need to know the failed tests. This PR adds that to the ftw pipeline. Go-ftw still needs to have the feature built.
=> ci: be less verbose in ftw tests

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920540.yaml
This PR resolves the second part of issue #2512 by adding a new rule and tests.
I'm not sure how common Unicode characters are in requests. Therefore I added detection of Unicode characters in form `\u0061` as new rule at PL2. We can move this rule to an other PL if needed.
There is a similar rule I found at PL1 which detects Unicode in the form `%uff00`: [920260](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L457).
See referenced issue for more info and conversation.
=> fix(unicode bypass) issue #2512

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941400.yaml
This PR fixes a XSS bypass technique that could bypass the ruleset at PL3
since the syntax is really simple and well known (now) I decided to put the rule at PL1.
Fixes #2777.
=> fix(xss): bypass JavaScript function without parentheses

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921240.yaml
This PR resolves issue #2509 by adding a new rule 921240 at PL1 and a test.
The rule detects `unix:[^|]*\|` in `REQUEST_URI` and the reported attack `GET /?unix:AAAAAAAAAAAAA|http://coreruleset.org/` is detected.
See referenced issue for more information and conversation.
=> feat(CVE-2021-40438): add rule 921240 mod_proxy attack detection

.github/workflows/go-ftw.yml
This makes sure changes to the artifacts like filename don't affect the workflow
=> Use tagged release for go-ftw download

rules/REQUEST-901-INITIALIZATION.conf
PR fixes #2812.
Removes the rules checking and setting the now redundant variables `TX:do_reput_block` and `TX:reput_block_duration` (they were moved into a plugin and out of the core CRS).
=> fix: remove reputation variables

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942320.yaml, util/regexp-assemble/data/942320.data
This PR resolves issue #2870 (SQLi bypass submitted by Shivam Bathla) by adding detection of `::bool` and `::int` data conversion in PostgreSQL.
Rule 942320 is the only PostgreSQL rule that I think is a good match for this extension.
I think `::int` and `::bool` are not so prone to FP, so I think extending this PL1 makes sense.
This rule will solve most of Shivam's reported findings.
I'll ask him over email if he can take a look too.
Closes #2870.
=> Add sql data conversion ::int and ::bool

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
'cat /etc/passwd' assigned via individual variables, cat in reverse order:
```
exec=c4=\ ;c3=t;c2=a;c1=c;a1=/;a2=e;a3=t;a4=c;a5=/;a6=p;a7=a;a8=s;a9=s;a10=w;a11=d;$c1$c2$c3$c4$a1$a2$a3$a4$a5$a6$a7$a8$a9$a10$a11
```
=> test: new test in 932200 for individual variables assignment

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932130.yaml
Hello! 
Similar to https://github.com/coreruleset/coreruleset/pull/2168, I found that tests from `932130-12` to `932130-16` have the `uri` parameter that does not start with a path like `/`. Looking at rule [`932130`](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf#L370) and relative [tests](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932130.yaml), seems to me that the missing path is not related to what the tests are intended for (command injections inside URI parameters).
All the affected tests are true tests, and, with this fix, they are correctly detected by Coraza running on a simple Go-http server.
Setting PR Draft status because I wish to test it against …
=> Fixes 932130 tests urls

tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934130.yaml
Fixes #2861.
Simply removing a test with a duplicate payload that was already covered by another test in the same yaml file.
There are several payloads which work on multiple frameworks/backends, so I made a small selection of interesting ones to ensure the rule covers as much as possible.
These two different vulns were vulnerable to the same payload and apparently I did not notice that.
So it is a true duplicate.
=> fix(934130): remove unnecessary duplicate test

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942101.yaml
This PR:
- Adds `REQUEST_FILENAME` to `942101`: libinjection is usually not matching strings with a leading path (being interpreted as a not unary arithmetical operator), but quotes and comment blocks lead to correctly evaluating some SQLi crafted inside the URL (e.g. `/foo/24'union all select/bar`).
- Moves `942101` to PL2: although single quotes can be common in languages like French and Italian, after it, a valid SQL statement is required in order to match the rule. PL2 seems to be a good fit: it already assumes consciousness of possible false positives, but it is low enough to provide security in most real-life scenarios that are looking for it. 
As a side note, other libinjection SQLi checks are made at PL1 (rule `942100`).
- Adds related tests.
=> fix(ULYKOFYK-2): adds REQUEST_FILENAME to 942101, moves to PL2

rules/REQUEST-901-INITIALIZATION.conf
This PR removes the rule which initialized the `TX:high_risk_country_codes variable`, because libmodsecurity3 does not support that form of value giving - see this [comment](https://github.com/coreruleset/coreruleset/pull/2921#issuecomment-1299089649). It was just a cosmetic rule, it is not necessary for the correct working of rule set.
With that, Nginx couldn't start - now everything is fine. The PR is ready for review and merge.
=> fix(nginx setvar syntax) Remove initialize rule as libmodsecurity does not support empty value ginivg

util/regexp-assemble/lib/processors/template.py, util/regexp-assemble/tests/preprocessor_test.py
See https://github.com/theseion/crs-toolchain/issues/24
=> fix: match all occurrences of template regex on a single line

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920610.yaml
Every CI run is now outputting a warning:
```
Check warning on line 22 in tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920610.yaml
GitHub Actions / check-syntax
22:3 [comments-indentation] comment not indented like content
```
I hope this fixes it?
=> fix(920610): CI is complaining about indented comment

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
These commits fixed few issues:
* Fix action order in crs-setup.conf.example
* Removed paranoia-level/N tags from rules, which contains `nolog` action
* Set default value for uninitialized TX variables
* Set correct TX score variable, according to rule's `severity` value
* Moved audit log part E if there is a chained rule, see [#2531](https://github.com/coreruleset/coreruleset/pull/2531)
=> fix(ruleset scoring and tagging): Fix PL related issues in v3.2/dev

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
Looks like somehow these variables were not updated with the big renaming. This PR updates the name.
=> fix: update PL TX variables to new naming

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, util/regexp-assemble/data/942240.data
This PR closes #2859 by disassembling data file of 942240. @theseion confirmed that it doesn't make sense to disassemble 94230. So I did not touch this one.
The generated rule looks a bit different (also according to `regexp-assemble.py compare`) but it's still valid.
=> fix(regex 942240) - disassembled data file

tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942500.yaml
This PR adds test for status page 942500-2 and also fixes 942500-1 so that this only triggers one rule.
It was accidentally POST request without request body.
=> feat(test) - add status page test for 942500

tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942270.yaml
This PR adds the test 942270-2 that only triggers this one rule. Intentionally missing word boundary at the start so that this test does not trigger other sqli detection rules.
=> feat(test) - add status page test for 942270

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920250.yaml
PR adds a status page test for rule 920250 (a new test which only triggers this specific rule).
**Important:** The 920250 tests are _disabled_ by default (see `enabled: false` at the top of the test file). I don't know why they're disabled, but this is important to be aware of if attempting to use this new test.
=> Add status page test for rule 920250

tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941240.yaml
This PR adds status page test 941240-2 with `<importimplementation=` intentionally without space to only trigger this one rule.
=> feat(test) - add status page test for 941240

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932130.yaml
If I'm not missing something, we need a `%5D` here instead of `%D`.
I wonder how the test 032130-9 could pass as is...
maybe we need to investigate, isn't it?
=> fix(test): fix encoded square bracket

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932140.yaml
this PR fixes the 932140-3 test, by encoding character % to %25
=> fix(test): missing encoding on % char

tests/docker-compose.yml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920250.yaml
- enable variable `VALIDATE_UTF8_ENCODING`
- now that tests use markers, remove unused `TZ`
Fixes #2983.
=> test: enable utf8 encoding validation

.github/workflows/lint.yaml
Re-enable lint check for updated regexes.
=> feat: use crs-toolchain for linting

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932180.yaml
932180-2 has a broken MIME header. This breaks the test unless the server is configured to ignore recommended rules 200002 and 200003. This fixes the MIME header.
=> Fix (932180): Correct multipart headers in test 932180-2

rules/lfi-os-files.data, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930120.yaml
Fixes failing curl calls for EH5C5EUO.
=> Add `subuid` to lfi-os-files.data

rules/php-config-directives.data, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933120.yaml
Fixes failing curl calls from NFKUWKBD.
@theMiddleBlue I'm not entirely sure that all of these directives pose security threats. But they were part of the original report and @azurit put them into the curl calls.
=> Add missing entries to php-confi-directives.data

rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/RESPONSE-980-CORRELATION.conf
This PR contains two small commits:
* Removed unused TX variables (`real_ip` and `942521_full`)
* Initialize and use once `anomaly_score` TX variable
With this PR, all TX variables in CRS will be initialized and used at least once.
This will close #2990.
=> Cleaning up TX variables

regex-assembly/942190.ra, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Update 942190.data and rebuild rule with crs-toolchain. Needed to replace :space: :^space: due to apache incompatibility. Needed to remove nested bracket for :space: and :nospace: inside character class"
[i2856 4967794a] Update 942190.data and rebuild rule with crs-toolchain. Needed to replace :space: :^space: due to apache incompatibility. Needed to remove nested bracket for :space: and :nospace: inside character class
=> fix 942190 : Update 942190.data and rebuild rule with crs-toolchain.

regex-assembly/942550.ra, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942550.yaml
This PR contains a new rule at PL1 that tries to catch SQL in JSON payloads not covered at PL1. For more information about the bypass technique, please refer to https://claroty.com/team82/research/js-on-security-off-abusing-json-based-sql-to-bypass-waf
=> New rule 942550 (PL1) JSON in SQL

regex-assembly/934101.ra
=> chore: update 934101 to use regex-assembly

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
PR adds `REQUEST_FILENAME` to rule 942120 at PL 2: _SQL Injection Attack: SQL Operator Detected_. A new test is also added.
This change allows us to detect path-based SQLi attempts like
`localhost/rest/products/2499999||this.product/reviews`
by matching against SQL operators in paths.
This PR should fully resolve bug bounty issue ULYKOFYK.
Associated issue: #2977
=> Add REQUEST_FILENAME to 942120 to catch path SQLi

rules/java-classes.data
Added the relevant information needed to explain the use and need for the java-classes.data file. Since information on the exploit tester and CVEs already exist in the 944 file, I simply mentioned the rule, and the associated CVEs with links. 
Being the first PR, I'm not sure if this is the correct syntax style, and if the information added gives enough information.
=> feat: add relevant info for java-classes.data

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932220.yaml
This test add coverage for BB finding 9P5LL13Y.
Fixes #2793.
=> test: add coverage BB finding 9P5LL13Y

.github/workflows/pr.yaml
This PR adds a check to enforce titles follow the conventional commits specification.
=> feat(ci): add check for conventional commit PR title

regex-assembly/933210.ra, regex-assembly/933211.ra, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933211.yaml
referring to #2581 
the bb test works as expected on sandbox (payload blocked at PL3 by 933211)
```
$ curl -i -H "x-format-output: txt-matched-rules" -H "x-backend: apache" -H "x-crs-version: nightly" -H "x-crs-paranoia-level: 3" "https://sandbox.coreruleset.org" -G --data-urlencode "code=(sy.(st).em)(@id)"
HTTP/1.1 200 OK
Date: Wed, 23 Nov 2022 09:20:17 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
X-Unique-ID: Y33l0Z2dMj7W2sk7D7FPGQAAAJI
x-backend: apache-nightly
933211 PL3 PHP Injection Attack: Variable Function Call Found
942431 PL3 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)
949110 PL1 Inbound Anomaly Score Exceeded (Total Score: 8)
980170 PL1 Anomaly Scores: (Inbound Scores: blocking=8, detection=8, …
```
=> fix(data): optimized regex for 933211 w/ crs-toolchain

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf, rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf, rules/RESPONSE-950-DATA-LEAKAGES.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf, rules/RESPONSE-955-WEB-SHELLS.conf
Since the response body could contain personal/sensitive data, it should not be logged and stored anywhere.
A false positive intercepted by a rule could contain unwanted data on logs.
This PR removes all `ctl:auditLogParts=+E` from all rules
> E: Intermediary response body (present only if ModSecurity is configured to intercept response bodies, and if the audit log engine is configured to record it. Intercepting response bodies requires SecResponseBodyAccess to be enabled). Intermediary response body is the same as the actual response body unless ModSecurity intercepts the intermediary response body, in which case the actual response body will contain the error message (either the Apache default error message, or the ErrorDocument page).
=> fix(rules): remove response body from logs

README.md
Just update the year. Also add some spacing to better read the output.
=> chore: update copyright year on README

.github/workflows/stale.yml
Per dialog and decision in our DEV retreat, let's mark as stale only issues that are labeled `awaiting feedback` only, and shorten times to closing.
=> feat(ci): only close issues awaiting for feedback

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Removing the residue `ctl:auditLogParts` action.
Previous PR was #3034.
Note: I've modified rules-check.py script, added the function which checks that `ctl:auditLogParts` exists or not. After the first test, I found these two occurrences.
After we merge this PR, I can add the final version of rules-check.py script with documentation and examples.
=> fix(rules): remove residue response body from log

regex-assembly/942320.ra, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942320.yaml
This PR adds additional PostgreSQL data types. Shivam reviewed my [latest changes](https://github.com/coreruleset/coreruleset/pull/2872) and found new data types. He also provided PoCs.
This PR here makes the coverage or the detection more robust.
Source is: https://www.postgresql.org/docs/current/datatype.html.
But not every data type can be used to craft an attack.
And this PR also fixes a bypass with multiple (`*`) + and - characters before numbers, not only 0 or 1 (`?`).
So this PR fixes 2 of the 6 new bypasses submitted by Shivam: https://github.com/coreruleset/security-tracker-private/issues/4
=> fix(942320) - add postgres data types and multiple plus minus signs

regex-assembly/toolchain.yaml
The toolchain configuration file stores configuration that must be part of the CRS repository. For now, this information is limited to the anti-evasion patterns used by the cmdline processor of the toolchain.
See https://github.com/coreruleset/crs-toolchain/pull/70
=> feat: add configuration file for toolchain

.github/workflows/test.yml
Should solve this:
"regression (modsec2-apache)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/."
=> fix(ci): updating to actions/upload-artifact@v3

tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921120.yaml
PR adds a status page test for rule 921120 (a new test which only triggers this specific rule).
=> fix: add status page test for rule 921120

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942200.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942370.yaml
This PR adds request headers referer and user-agent to two PL2 rules:
* 942200
* 942370
* 
This PR also adds tests with PoC commands from Shivam Bathla.
For more info see: https://github.com/coreruleset/coreruleset/issues/2924
=> fix: add headers to pl2 rules 942200, 942370

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942521.yaml
This PR adds 2 request headers to rule 942521: user-agent and referer.
This PR also adds PoC provided by Shivam Bathla as new regression tests.
For more info see: https://github.com/coreruleset/coreruleset/issues/2924
=> fix: add headers to pl2 rule 942521

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
This PR adds request headers referer and user-agent to pl2 rule 932200.
This PR also adds Shivam Bathla's PoC request as regression test.
For more info, also see: https://github.com/coreruleset/coreruleset/issues/2924#issuecomment-1382397292
=> fix: add headers to pl2 rule 932200

rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/php-errors-pl2.data, rules/php-errors.data
Some of the patterns in `php-errors.data` are too common to be in PL1 so i'm moving them into PL2. I also removed a whitespace from the beginning of few patters as it's trimmer by modsec anyway.
=> fix: PHP errors data file

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf
As mentioned in the slack channel, these headers should not be used by legitimate requests. They can however be used for attacks, as described f.ex. here: https://www.sidechannel.blog/en/http-method-override-what-it-is-and-how-a-pentester-can-use-it/
Signed-off-by: Mark Zeman <zeman@puzzle.ch>
=> feat: add method override headers to restricted headers, rules 900250 and 901165

tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934130.yaml, tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934131.yaml
Hi!
Sibling of https://github.com/coreruleset/coreruleset/pull/2880. There are some positive tests in which the `uri` is not starting with a `/`. Go server and Envoy deny these requests with a `400`, therefore tests fail and the real payload that we are trying to analyze is not checked.
The tests are about JavaScript prototype pollution injection attempts, I don't think that it was intended to try to specs/rfcs regarding the path format.
Thanks!
=> fix: few invalid uri for 934130 and 934131 tests

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920280.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920430.yaml
`920280-3`, `920430-3` and `920430-9`  tests are performing requests with http version <= `HTTP/0.9`. Depending on the server, I'm experiencing different behaviours (and status codes returned).
This PR proposes to add status codes  `505` (`HTTP Version Not Supported`) and `426` (`Upgrade Required`) as accepted statuses for these tests in order to make them compatible also with, respectively, Go/http and Envoy proxy.
Thanks!
=> chore: adds 426 and 505 status codes for HTTP/0.9 tests 

regex-assembly/932237.ra, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932161.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
This PR adds 2 new rules to detect RCE in User-Agent and Referer request headers:
- 932161 at PL2 (unix commands with path)
- 932237 at PL3 (short and log unix commands without path, without prefix but with word boundary)
932237: 
I want to detect short commands like `id`, `env` and `set` in User-Agent and Referer request header.
932161: 
I want to detect unix commands with path in request headers User-Agent and Referer.
I hope I got his right and would be happy if @theseion could do a review :pray:
=> fix: add rce detection in request headers

rules/php-errors-pl2.data, rules/php-errors.data
`[Sat Mar 11 15:45:19.636843 2023] [:error] [pid 292128] [client 103.80.153.172:51798] [client 103.80.153.172]`
`ModSecurity: Warning. Matched phrase "Static function" at RESPONSE_BODY. [file "/etc/modsecurity/`
`coreruleset/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "44"] [id "953100"] [msg "PHP Information Leakage"]` `[data "Matched Data: Static function found within RESPONSE_BODY"] [severity "ERROR"] [ver`
`"OWASP_CRS/4.0.0-rc1"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] `
`[tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116"]`
`[tag "PCI/6.5.6"] [hostname "blog.jitendrapatro.me"] [uri "/wp-admin/post.php"] [unique_id`
`ZAxUt5um5UuN8ldYD8BbMwAAAAE"], referer: https://blog.jitendrapatro.me/wp-admin/edit.php` …
=> fix: php-errors FP

crs-setup.conf.example
This PR formats `crs-setup.conf.example` file:
* puts the actions in the correct order
* set the correct indentations
This is necessary if we want to process the `crs-setup.conf.example` with all commented `SecRule`'s and `SecAction`'s to fix #3141 without adding an extra rule.
If we don't want to allow these modifications (in this PR), the other possible solution is that we ignore checking of indentations and order of actions in that file.
I prefer this solution (I mean the first one).
The next PR will contain that `rules-check.py` script process `crs-setup.conf.example` without comments in case of `SecRule` and `SecAction` lines (and next ones).
=> fix(config): format crs-setup.conf.example

util/crs-rules-check/rules-check.py
This PR modifies the `rules-check.py` script that during the parsing of the `crs-setup.conf.example` it removes the comments before `SecRule` and `SecAction` directives. This means it emulates that rules are valid part of CRS, and - for eg. - therefore it does not need to initialize the TX variables.
The next PR will contain the modification which removes the rules [901167](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-901-INITIALIZATION.conf#L223-L231) and [901169](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-901-INITIALIZATION.conf#L233-L240) from [REQUEST-901-INITIALIZATION.conf](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-901-INITIALIZATION.conf), therefore the `tx.enforce_bodyproc_urlencoded` and …
=> fix(feat): strip comments during the parsing of crs-setup.conf.example

.github/workflows/nightly.yml
The issue we are having with the nightly release being marked as draft is something that has happened to others: https://github.com/ncipollo/release-action/issues/317.
This PR tries to fix the issue by forcing the `draft` parameter to be always applied when the release is being updated.
Docs: https://github.com/marketplace/actions/create-release
=> fix: apply non-draft state to nightly release forcefully

.github/workflows/nightly.yml
Delete the release before recreating it. The GH API doesn't allow for changing the tag of an existing release.
See https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release.
=> fix: properly publish nightly release

crs-setup.conf.example, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-949-BLOCKING-EVALUATION.conf, rules/RESPONSE-959-BLOCKING-EVALUATION.conf
This patch just aligns some malformed rules.
Question: what about  [these](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/RESPONSE-980-CORRELATION.conf#L43-L69) rules? These are also malformed, and differs from our [policy](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/CONTRIBUTING.md#general-formatting-guidelines-for-rules-contributions).
=> fix(style): Format malformed rules

CONTRIBUTORS.md
Follows https://github.com/coreruleset/coreruleset/issues/3204 invitation to join the project as a developer. So glad to accept the invitation and open this PR.
=> chore: adds Matteo Pace to list of Developers

tests/docker-compose.yml
Both httpd and nginx images have a CMD set for their entrypoint. For both images this CMD is equivalent to what we want to run anyway, so specifying it in the entrypoint is actually wrong.
Additionally, the docker-entrypoint.sh script for nginx appears to have changed. It requires arguments that it will `exec`. The predefined CMD happens to be that required set of arguments.
=> fix: use the correct entrypoint defenitions for containers

rules/php-function-names-933151.data
Added functions that have been added to PHP since PHP 7.0. The following is the list of functions that are added in each PHP version update(Note, I've only added functions that I think are relevant):-
```
curl_multi_errno
curl_share_errno
curl_share_strerror
openssl_get_curve_names
session_create_id
session_gc
pcntl_async_signals
pcntl_signal_get_handler
```
```
stream_isatty
spl_object_id
ftp_append
mb_chr
mb_ord
mb_scrub
socket_addrinfo_lookup
socket_addrinfo_connect
socket_addrinfo_bind
socket_addrinfo_explain
```
```
array_key_first
array_key_last
gc_status
hrtime
net_get_interfaces
openssl_pkey_derive
```
```
password_algos
mb_str_split
openssl_x509_verify
pcntl_unshare
```
```
array_is_list
pcntl_rfork
fsync
fdatasync
```
```
curl_upkeep
mysqli_execute_query …
```
=> feat: added newer PHP functions

CONTRIBUTING.md
This PR resolves issue #3222.
PR adds the missing content that was added to the documentation contribution guidelines, and adds missing crs-toolchain links/references.
=> fix: Add missing content and crs-toolchain links

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920450.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920451.yaml
PR reworks the "restricted headers" mechanism so that there are two different lists (and sets of rules)
- Basic
- Extended
This allows for difficult headers like "Accept-Charest" to be handled: block at a higher PL, but not by default / at PL 1 due to a handful of potential false positives.
*PR relates to issue #3148*
=> fix: Rework restricted headers

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920430.yaml
Adding support for HTTP/3 protocol.
Fixes: https://github.com/coreruleset/coreruleset/issues/3246
=> feat: HTTP/3 support

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920620.yaml
This is the same as https://github.com/coreruleset/coreruleset/pull/3237, backported for the v3.3 branch.
=> feat: backport rule 920620

crs-setup.conf.example
Adds `HTTP/3` and `HTTP/3.0` into the `900230` rule description where default values are listed.
Related to https://github.com/coreruleset/coreruleset/pull/3218
Address https://github.com/coreruleset/coreruleset/pull/3218#issuecomment-1639672172
=> chore: adds HTTP/3 to 900230 description

SECURITY.md
We should always point to the latest version of the security policy.
=> docs: update security policy link

tests/regression/README.md
`900005` has been removed via https://github.com/coreruleset/coreruleset/pull/3232/commits/68ad8de395625ef09007edb4df73759b026908ab, but it should still come in handy for properly configuring the engine for testing purposes.
=> chore: adds back test config rule 900005

CONTRIBUTING.md
PR brings the CONTRIBUTING.MD document in the core CRS repo back in line with the HTML version over in the CRS documentation repo. (New content added regarding tests; made a hyperlink consistent across both versions.)
=> feat: Bring CONTRIBUTING.MD back in line w/ HTML version

regex-assembly/932200.ra, regex-assembly/932205.ra, regex-assembly/932206.ra, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932205.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932206.yaml
New rules 932205, 932206 to handle the Referer header explicitly.
The regular expression in 932200 leads to false positives against URLs
with query strings (due to the `?`). 932205 uses an additional prefix in
the regular expression that matches the first `?` so that the following
expressions will only match question marks that are part of the payload.
932206 uses an additional prefix to match only when the Referer value is
not a URL (which is illegal). 932206 is thus equivalent to 932200 but is
required to distinguish the case where the Referer header does actually
contain a URL.
Fixes #3180.
=> feat: target Unix commands in Referer header explicitly

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml
In #3300 a false positive in 932200 was fixed and tests were written to ensure that the FP was fixed but the tests target 932205 and 932206. This commit adds the same FP tests to 932200, the rule that originally exhibited the FPs.
=> chore: add FP tests to 932200

rules/php-errors-pl2.data, rules/php-errors.data, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953100.yaml, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
`File size is` phrase leads to false positives. [It has been agreed](https://github.com/coreruleset/coreruleset/issues/3279#issuecomment-1724191613) to move it from `rules/php-errors.data` to `rules/php-errors-pl2.data`. Now it will be matched by `953101`, at PL2. 
Closes https://github.com/coreruleset/coreruleset/issues/3304
=> fix: moves FP prone phrase `file size is` to PL2

rules/RESPONSE-950-DATA-LEAKAGES.conf
We reused paranoia level skip rules 950010, 950011, and 950018.
These rule identifiers were in use in CRSv2, so we used different identifiers in CRSv3 to avoid conflicts (950020, 950021 and 950022). In CRSv4, for the sake of a consistent structure, we use these identifiers again, so that the skip rules of PL can be defined in the same way for all files (rule_id MOD 100 < 20).
Rule id 950130 has been kept - this ID also was introduced at first rule to avoid the collision.
=> feat: Reuse rule ID's 950011, 950012 and 950018 for consistent operation

tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941100.yaml
The payload used on this test is loosely based on one of the examples on the portswigger XSS cheatsheet.
I took said payload and reduced it and re-encoded it to go around the other rules triggering. 
I also had to pick a JS event name that is not yet in use (or other XSS rule  941160 PL1 would trigger). I think this is warranted since there might always new JS events that 941160 does not yet detect.
So I think the result is a test that is isolated and still triggers on something that might be an attack.
=> feat: new isolated test 941100-6 (941100 PL1) (Christian Folini)

.github/workflows/test.yml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920181.yaml
Fixes 920181-1 pointing to /anything that supports POST requests and ensuring that the response code is `200`.
=> fix(test): 920181-1

regex-assembly/920260.ra, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
This PR fixes an issue related to PCRE/libModSecurity that prevents to match "uFF" with `[fF]{2}` regular expression syntax
=> fix: PCRE/libModSecurity related issue with regex

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
This makes sure the request is blocked instead of warning when anomaly threshold 5.
=> feat: raised severity to critical (920290 PL1) (Christian Folini)

rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
To address the compatibility issue between v2 and v3, this pull request removes the 'range' component from 941010 in favor of using `ruleRemoveTargetByTag`
=> fix: perf rule 941010

rules/php-errors.data
Fixes #3390.
Fixes https://github.com/coreruleset/wordpress-rule-exclusions-plugin/issues/25.
=> fix(PHP): Too common phrases matched

.github/workflows/create-changelog-prs.py, .github/workflows/update-changelog.yaml
- new workflow that runs once a day
- a python script that uses the gh CLI to find all the PRs that were merged the previous day and then creates one PR for each user who merged at least one PR
- the created PR is assigned the new label "changelog-pr"
Fixes #3368
=> chore: add workflow for automating changelog updates

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
There is an issue reported by @EsadCetiner on [Slack](https://owasp.slack.com/archives/CBKGH8A5P/p1702120465984659), namely in case of rule [932240](https://github.com/coreruleset/coreruleset/blob/d544d8d2ee1c739612958bf3c5a9c7bfc29f35bf/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf#L1135-L1157) triggering the target is not in the log - that is, it is there, but only the `MATCHED_VAR`.
The solution is the same as we use at rules [932206](https://github.com/coreruleset/coreruleset/blob/d544d8d2ee1c739612958bf3c5a9c7bfc29f35bf/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf#L1039-L1057) and [932200](https://github.com/coreruleset/coreruleset/blob/d544d8d2ee1c739612958bf3c5a9c7bfc29f35bf/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf#L961-L980): set a new TX variable by value of …
=> fix: Added missing target name to logdata

rules/php-errors-pl2.data, rules/php-errors.data, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953100.yaml, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
=> fix: solve false positive by shifting ``Field cannot be empty`` to PL2 (953100 PL1, 953101 PL2) (Esad Cetiner)

.changes-pending.md, .github/create-changelog-prs.py, CHANGES.md
- remove @ from real names in changelog lines
- write changelog entries to `.changes-pending.ms`, using `CHANGES.md` directly was confusing and polluted the changelog
- use conventional commit message for PR title
Fixes #3414
=> chore: improve changelog-pre workflow

.github/create-changelog-prs.py
- ignore changelog PRs when discovering PRs
- fix mapping code that accidentally would drop most PRs from being processed
=> fix: fix PR discovery

regex-assembly/933160.ra, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
A missing alternation in the regular expression for matching characters after PHP commands caused `#` comments and whitespace to be matched improperly.
This issue was discovered as part of #3201.
=> fix: fix whitespace matching after PHP command (933160 PL1)

.github/workflows/nightly.yml
The actions we've been using to publish the nightly release sometimes publish the nightly as draft and we have no idea why. We're now simply using the GH CLI to do the same thing. If that continues to be problematic it will hopefully be simpler to debug.
=> chore: try to fix draft nightlies by using GH CLI

.github/workflows/nightly.yml
The nightly release failed. Running the exact same script on my machine works.
=> chore: debug nightly release

CONTRIBUTING.md
I added the new section of Coreruleset's documentation how to run tests.
=> docs: Added link to run tests

.github/workflows/nightly.yml
The shell on the runner doesn't accept the `read -r -d '' name` format. Not sure why. I've replaced it with a sub shell expression (tested in a separate repository).
=> fix: don't use `read` for multiline variables

.github/workflows/nightly.yml
The nightly release is still being created as draft sometimes. Add additional step to verify state and publish release if necessary.
=> chore: verify nightly release state after creation

.github/create-changelog-prs.py
The PR body of a changelog PR can contain shell meta characters which cause PR creation to fail sometimes. Pass the body via stdin instead.
=> fix: use stdin to pass PR body to gh CLI

tests/docker-compose.yml
httpbin does not properly reflect Unicode sequences but returns JSON Unicode escape sequences instead. This can break response tests that rely on the data in the response to be an exact copy of the request data. See https://github.com/coreruleset/go-ftw/issues/198.
This PR switches the backend for tests from httpbin to the go-httpbin port, as the port behaves correctly.
=> fix: JSON Unicode reflection for tests

rules/REQUEST-922-MULTIPART-ATTACK.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Adding missing comments about `regex-assembly` to rules `922110` and `942440`.
=> fix(comments): Comments update (922110 PL1, 942440 PL2)

regex-assembly/932130.ra, regex-assembly/932131.ra, regex-assembly/include/932130.ra, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932131.yaml
The Facebook for Android user agent uses a bracket sequence in the user agent string which triggers FPs for rule 932131. The analysis revealed that this issue had already been fixed in 932130, the sibling rule with the same regular expression, but that the regex-assembly file for 932131 did not exist, which is why the regular expression was not updated.
Fixes #3483
=> fix: prevent FP against brackets in User-Agent header

rules/scanners-user-agents.data
The tool itself is an open source project by Google, though it has been used by the usual suspects to scan various targets.
=> feat: add User-Agent of Tsunami Security Scanner

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920201.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920202.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920440.yaml, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921240.yaml
This applies to variables for `REQUEST_URI`, `REQUEST_BASENAME` and `REQUEST_FILENAME`.
ModSec3 does an implicit URL decoding on phase 1 and the same on phase 2.
ModSec2 does no implicit URL decoding on phase 1, but it does it on phase 2.
This allows an attacker to URL encode a URI and bypass detection on phase 1 rules on ModSec2.
Example:  920440 PL1 should detect this: `/dump%2Erdb` as an encoded version of `dump.rdb`.
However it fails do to so in the v4 dev tree.
It used to work up to CRS v3.3, because rule 920440 used to run in phase 2, but when we introduced early blocking for CRS v4, we shifted 920440 and several other rules from phase 2 to phase 1 and the implicit decoding of the payload (see above) was removed for ModSec 2 and we no longer detected the attack.
Unfortunately, this …
=> fix: Added t:urlDecodeUni for REQUEST_URI / REQUEST_BASENAME checks in phase 1 (921240 PL1, 920440 PL1, 920201 PL2, 920202 PL4)

rules/restricted-files.data
Adding `BlockCypher.log` into `restricted-files.data` which is a log file name used in code examples. Currently actively accessed by bots.
=> feat: Adding BlockCypher.log into restricted-files.data (930130 PL1)

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942440.yaml, util/find-rules-without-test/find-rules-without-test.py
Facebook and Google ad platforms append a query argument to URLs that can contain consecutive sequences of dashes, triggering 942440 in error. This commit adds two rules to exclude these arguments from 942440.
Fixes #2981
Fixes #3005
=> fix: prevent FPs against click identifiers in query

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
We decided that this rule produced too many FPs at paranoia level 1. We were discussing removal but settled for moving the rule to paranoia level 2 for v4 and revisit removal later.
Note: the gist of this rule appears to be protection against errors in application level decoding.
=> feat: move 920240 to PL2

regex-assembly/920220-chain1.ra, regex-assembly/920221.ra, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920220.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920221.yaml
- use `t:urlDecodeUni` to ensure that the URI has been decoded in phase 1
- don't check the last path segment in 920220
- check the last path segment in new rule 920221, only if it does not look like a file name
- fix tests of 920220 to satisfy the following criteria:
* the raw request URI must have valid encoding
* if the decoded last path segment is a file it must not be checked for invalid URI encoding
* validate the decoded URI (except for file name)
=> fix: reduce FPs in 920220

rules/restricted-files.data
Removing keyword `/.env` as it's already covered by `.env` on line 19.
=> fix: Removing duplicate keyword (930130 PL1)

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
932260 was copied from 932240, which includes a chain rule to prevent false positives against number separators. This chain rule makes no sense for 932260 and is actually detrimental, as it enables trivial bypasses.
=> fix: remove chain rule from 932260

regex-assembly/942500.ra, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942500.yaml
- Detection of optimizer hint comments in MySQL was broken because of the use of `urlDecodeUni`, which converted the `+` character into a space. The rule now uses `multiMatch` to detect the `+` character with and without URL encoding
- The original rule did not take into account that whitespace is optional before the comment modifiers. This comment fixes that issue.
Fixes #3359
=> fix: detect MySQL optimizer hints

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
This PR fixes the listed behaviors under issue #3428. The solution is similar like in case of #3409.
changelog comment:
fix: Added missing target name to logdata (942521 PL2, 943110 PL1, 943120 PL1) (Ervin Hegedüs)
Fixes #3428
=> fix: Replaced MATCHED_VAR in logdata argument by a real target name

.github/create-changelog-prs.py
The CHANGES.md file uses a leading space in front of the asterisk. Generate the changelog entries in the same format so that it's easier to copy entries.
Fixes #3547
=> chore: generate changelog entries with leading space

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
A few RCE rules are only inspecting the HTTP headers in phase 2. These rules don't need access to the data in phase 2 and can be ran in phase 1 with a small performance boost.
closes https://github.com/coreruleset/coreruleset/issues/3458
=> perf: move 932237, 932205, 932206 and 932161 to phase 1

tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
As per [rfc9110](https://httpwg.org/specs/rfc9110.html#method.overview), `method` is case sensitive. Because of this, `932260-28` is failing against Envoy that is returning `400` and go-httpbin that returns `405 Method Not Allowed`.
=> fix(test): 932260-28 http method uppercase

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
This PR removes the `t:lowercase` transformation from rules where the `@rx` operator uses `(?i)` modifier.
This needs to merge before #3584 will merged.
=> fix: Remove t:lowercase from rules what use '(?i) modifier in their regex

rules/REQUEST-901-INITIALIZATION.conf, rules/REQUEST-905-COMMON-EXCEPTIONS.conf, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-949-BLOCKING-EVALUATION.conf, rules/RESPONSE-959-BLOCKING-EVALUATION.conf, rules/RESPONSE-980-CORRELATION.conf
Adding missing tag `OWASP_CRS` to (almost) all rules so it's all disabled when using `ctl:ruleRemoveByTag=OWASP_CRS`.
Also adding missing `ver` action to (almost) all rules.
Not sure if tag `OWASP_CRS` should be added also to rules used for skipping paranoia levels and anomaly score reporting rules in `RESPONSE-980-CORRELATION.conf`.
=> fix: adding missing tags and ver action

crs-setup.conf.example, rules/REQUEST-911-METHOD-ENFORCEMENT.conf, rules/REQUEST-913-SCANNER-DETECTION.conf, rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-922-MULTIPART-ATTACK.conf, rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf, rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf, rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf, rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf, rules/REQUEST-949-BLOCKING-EVALUATION.conf, rules/RESPONSE-950-DATA-LEAKAGES.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf, rules/RESPONSE-955-WEB-SHELLS.conf, rules/RESPONSE-959-BLOCKING-EVALUATION.conf, rules/RESPONSE-980-CORRELATION.conf
- Adding missing tag `OWASP_CRS` to everywhere.
- Adding missing `ver` action to everywhere.
- Reordering tags in some rules to unify tag order.
=> fix: adding more missing tags and ver actions

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920100.yaml, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920300.yaml, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941100.yaml, tests/regression/tests/REQUEST-949-BLOCKING-EVALUATION/949110.yaml
As discussed on slack, replace cnn.com with coreruleset.org to make tests neutral
=> refactor: Replace cnn.com with coreruleset.org

CONTRIBUTORS.md
CC @53cur3M3, @emphazer, @spartantri, @theMiddleBlue, @csanders-git, @fgsch, @studersi
We discussed this internally and talked to some of you already. This is now the step that reduces the CONTRIBUTORS.md file to the currently actively contributing developers. That means we kept everybody in the file for 4.0, but now we move forward with the consolidated team.
If you pick up contributing to the project again, then you'll move to the developers section of course.
=> chore: consolidate CONTRIBUTORS.md after 4.0

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/lfi-os-files.data, rules/restricted-files.data, rules/restricted-upload.data
``lfi-os-data`` already included Roundcube's ``config.inc.php`` but it was missing from other data files as well as ``config.sample.php`` and ``defaults.inc.php``. I've added Roundcube's example config files as well just in case someone left a database password in there.
=> fix: add missing roundcube files (930120 PL-1, 930121 PL-2, 930130 PL-1, 932180 PL-1)

.github/workflows/lint.yaml, .github/workflows/test.yml
To prevent unexpected results when running pipelines, pinning versions in our tools will allow us to make controlled deployments.
=> fix: pin tool versions in gha

rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
It was agreed to remove 942110 due to causing many false alarms without providing much value, however some traces of the rule remains in the code comments. https://github.com/coreruleset/coreruleset/issues/3466#issuecomment-1904742398
=> chore: remove references to nonexistant 942110 rule

rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920520.yaml
This PR resolves #3623 by increasing the length of accepted Accept-Encoding headers from 50 to 100 (according to decision in [monthly chat meeting in April](https://github.com/coreruleset/coreruleset/issues/3636#issuecomment-2031698769)).
This PR also adds a test to ensure that internet.nl values no longer trigger FP.
Please also note that regression test 920520-7 still works.
=> fix: increase length of Accept-Encoding header from 50 to 100 (920520 PL1)

.github/workflows/nightly.yml, .github/workflows/update-changelog.yaml
Running workflows that use the GH API at the same time is a bad idea because it's easy to run into API rate limits that way.
=> fix: run nightly workflows at separate times

.github/workflows/test.yml
The httpd container runs with a UID that differs from the host and is no longer root. On the GH runner, this apparently prevents files from being created in the logs directory.
=> fix: fix permissions of log files for tests

regex-assembly/933100.ra, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933100.yaml
This PR is the second PR that should resolve #3616.
It adds a new detection for `xml\s*[^a-z]` (ignore case). 
Thank you @floyd-fuh for the false negative report and for providing a detection regex.
This PR also adds some tests: false negative test and uppercase test
=> fix: add detection for php evasion attempt (933100 PL1)

rules/unix-shell.data, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
I was supposed to add cscli and visudo to ``unix-shell.data`` in https://github.com/coreruleset/coreruleset/pull/3649 but I forgot about it, this pr fixes that.
=> fix: add visudo and cscli to unix-shell.data (932160 PL-1, 932161 PL-2)

.github/create-changelog-prs.py, .github/workflows/update-changelog.yaml
- The idea to base changelog PRs off each other didn't work out. Merging a newer changelog PR before its older predecessor led to a ton of conflicts. This PR reverts to the previous behavior of basing all changelog PRs on the main branch.
- In order to reduce the workload, changelog PRs are now created weekly on Sunday.
- In order to improve handling and debugging, PRs are checked against previously merged changelog PRs and excluded if found.
- The workflow can now be manually triggered from the GitHub UI. This operation is safe because the PRs are checked agains previous changelog PRs.
=> chore: create changelog PRs weekly, based on main

regex-assembly/951240.ra, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
Catch Java error messages similar to this:
`org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_1t68827l97cwyxo9r1u6t4p7d"
`
=> feat: catch Java PostgreSQL errors (951240 PL1)

regex-assembly/951120.ra, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
I'm getting FPs with this part of regex matching Oracle SQL error messages:
`Oracle.*Driver`
Was trying to find what kind of error messages is this regex supposed to match and was able to found only these:
```
Cannot initiate JDBC driver with class name oracle jdbc Oracle Driver
[informatica][Oracle JDBC Driver][Oracle]Connection refused
JDBC Driver class not found: oracle.jdbc.OracleDriver
```
My fix expects that the last one may be in the form of `oracle.jdbc.Oracle<something>Driver` (but i haven't found any on the web) and for this case the 20 characters limit seems to be sufficient.
Also, this PR fixes other FPs, for example:
```
<URL>https://www.example.com/rainbow-loom-gumicky-trikolora-20721/</URL>
41-npr-devinska-kobyla-_-florora-693027.jpg
```
All Oracle error codes which i was …
=> fix: Oracle SQL database data leakage FP (951120 PL1)

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920330.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942280.yaml
In https://github.com/coreruleset/coreruleset/blob/31ee4883c74e098e22ca69acd1c15a8a63ad94c4/tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920330.yaml#L5 the value of name is `920320.yaml`, as opposed to the actual filename of `920330.yaml`
In https://github.com/coreruleset/coreruleset/blob/31ee4883c74e098e22ca69acd1c15a8a63ad94c4/tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942280.yaml#L40 there is a missing trailing double quote in the `log_contains` field
=> fix: typos in 920330 and 942280 tests

tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953100.yaml, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
In most instances (within tests at least) priority level 1 and 2 are referred to as `PL1` and `PL2`. 
In a couple of instances they are referred to as `PL-1` and `PL-2`; breaking the common terms used.
=> test: change pl-1 to pl1 to be inline with others

rules/RESPONSE-950-DATA-LEAKAGES.conf, rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf, rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf, rules/RESPONSE-955-WEB-SHELLS.conf
There is no sense in searching for any patters in compressed data.
=> feat: skip response rules if data are compressed

tests/docker-compose.yml
_Fixes: #3738._
The CRS Docker containers were recently changed to go root-less. This broke testing setups as the Docker bind mounts now run into permissions issues that prevent the CRS test containers from starting (the containers cannot write to the filesystem by default any more and the containers fail at startup).
For the purposes of running the CRS testing setup without issue:
**This PR:**
- Uses the Docker `user` directive to override the user that is used to run the testing container processes, setting them back to root like before. This means that the CRS testing setup that we ship once again "just works" out of the box
- Adds appropriate documentation warnings to the docker-compose file warning users not to blindly copy this setup with `user: root`
=> fix: add 'user: root' directives and explanations

.github/workflows/test.yml
_Depends on: #3757._
@theseion As discussed, this PR removes the `chmod` workarounds from the testing pipeline.
I _think_ these are the necessary changes… It seems simple enough :slightly_smiling_face:
=> chore: remove chmod workarounds to simplify test workflow

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
The conditions of the removed tests are already covered by 920530
Fixes #3692
=> test: remove redundant commented tests in 920480

tests/docker-compose.yml, tests/regression/httpd-overrides.yaml, tests/regression/nginx-overrides.yaml
- activates existing variable to be used in tests
Fixes #3745
=> fix: enable checking ARG_LENGTH in tests

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932300.yaml
932300 should have the `capture` action since `TX.0` is used in `logdata`. Currently, `TX.0` will simply contain the last value assigned to it by any previously run rule.
Fixes #3761
=> fix: use proper capture for log output of 932300

tests/docker-compose.yml
In https://github.com/coreruleset/coreruleset/commit/50a1fdf875fd4d5b1c204f4db5cead5fd23700b9 we added the check for argument length, but it was added as boolean when it should have been an integer.
=> fix: use correct value to trigger test

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Variable no longer necessary since #3521 removed chain rule.
=> fix: Remove nonnecessary variable (932260 PL1)

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920540.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932210.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942330.yaml
Certain test descriptions contain escape sequences such as `\n` and `\a`.
These should be treated as literals, as opposed to being interpreted by Yaml. 
Changing from double quotes to e.g. block scalar syntax will also fix this, but that may be introducing extra whitespace/newlines which may not be wanted.
Changing to single quotes as I have done keeps the diff as small as possible, though single quotes do need to be escaped with another single quote, as is done in https://github.com/TimDiam0nd/coreruleset/blob/48fd95ef0999e90c1b4dc2a42ed8048c1646e3c2/tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml#L168
and https://github.com/TimDiam0nd/coreruleset/blob/48fd95ef0999e90c1b4dc2a42ed8048c1646e3c2/tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932200.yaml#L184 …
=> fix: test - description escaping

.github/workflows/test.yml
Regression tests are failing because the ``docker-compose`` command is no longer being recognized. Docker is now using ``docker compose``
https://github.com/coreruleset/coreruleset/actions/runs/10226259306/job/28315644800#step:4:21
=> fix: update ``docker-compose`` to ``docker compose``

rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Rule 932270's version was wrong, fixed it.
=> fix: Update 932270's ver

rules/REQUEST-921-PROTOCOL-ATTACK.conf
921180 works fine without the chained rule. It still correctly counts and blocks duplicate HTTP parameters
=> perf: remove unnecessary chain rule and capture for 921180

.github/workflows/lint.yaml, util/crs-rules-check/README.md, util/crs-rules-check/examples/test11.conf, util/crs-rules-check/examples/test12.conf, util/crs-rules-check/rules-check.py
Add two new features for `rules-check.py` linter:
* check that all rules have a `tag` with `OWASP_CRS`
* check that all rules have `ver` action with correct version string
Version can be passed manually with `-v`/`--version`. If no argument given, the script tries to get that from output of `git describe --tags`.
How the version is determined:
* eg `git describe --tags` gives string `v4.5.0-6-g872a90ab`
* `-6-` means there are 6 commits after `4.6.0`, so this is a `dev` version
* in this case we increment MINOR version: `5` -> `6`
* and version gets `-dev`
* the result will be: `4.6.0-dev` (`v` will be removed from the start position)
* if the version string is something like this: `v4.5.0-0-abcd01234` then the version will be `4.5.0`
In all cases the `OWASP_CRS/` prefix will be appended.
=> feat: Check that all rules have the correct CRS tag and version

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf, tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920440.yaml
Private keys can be stored in a .pem format, for example Certbot does this.
=> fix: add pem to restricted file extensions

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920430.yaml, tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Two typos:
- 932235 - test id 38 - had `no_expectIds` instead of `no_expect_ids`
- 920430 - `expect_ids` was directly under `output`, instead of being nested under `log` i.e. `output` -> `log` -> `expect_ids`
=> fix: tests typos

rules/REQUEST-922-MULTIPART-ATTACK.conf, tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
Add a new rule `922130` which check if any MULTIPART header contains a non-ascii character.
Fixes 3MU-240701-1 by @luelueking for v3.
=> feat: add new rule to catch invalid character in multipart headers (v3)

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920181.yaml
`stop_magic` has been replaced with `autocomplete_headers` as per the recent test schema change in 4.5. It looks like this somehow slipped through the cracks
=> fix: old schema field `stop_magic` in 920181.yaml

rules/restricted-files.data
File `sendgrid.env` contains API key for SendGrid service. It's already actively accessed by bots.
=> feat: added sendgrid.env into restricted files

.github/workflows/lint.yaml
Enables back the linter check.
There is a pending issue #3828 on this one.
=> ci: enable linter check back

util/change-version/change-version.py, util/crs-rules-check/rules-check.py
Fixing two alerts for [pylint intervention experiment](https://github.com/coreruleset/coreruleset/issues/3835)
The plan was 3 [interventions](https://github.com/evidencebp/pylint-intervention/blob/main/interventions/candidates/coreruleset_coreruleset_interventions_September_27_2024.csv)
Changes are minor
- The first long line represented the output and should stay as is
- Unneeded parentheses were removed when calling the del keyword
- Add line breaks to two too long lines making them shorter
Each intervention was done in a dedicated commit with a message explaining it.
@fzipi
=> refactor: 3835 pylint interventions

tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920270.yaml
test id 8 has been removed as it was a duplicate of test id 7. 
test id 9 has now been renamed to test id 8.
=> fix: remove duplicate test for 920270

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933120.yaml
- rule should match on PHP configuration modification attacks
- uses pmfromfile to match config names
- then there should be an equal sign, and the value to modify
👉 modify the rule to have a value after the equal sign, so it is relevant to what we try to match.
- rule is matching on base64 encoded strings with double equal signs
Fixes #3723
=> fix(933120): do not match on base64 encoded strings

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933120.yaml
This PR fixes a bypass introduced in #3863 to fix false positives with base64 encoded requests with double equals sign. This rule can be bypassed by either adding a white space, for example ``memory_limit = 512M`` or by supplying a path ``extension_dir=/path/to/example`` to a directive. I've used a negated set to avoid false positive with a double equals sign while also fixing the bypass.
=> fix: bypass by supplying whitespace or path argument (933120 PL-1)

.github/workflows/lint.yaml
- getting version in ci linting was broken for releases
=> fix(ci): get version when releasing from branch name

rules/REQUEST-921-PROTOCOL-ATTACK.conf, rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf, rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
As these rules are matching only against ARGS* variables, double URL decode can be removed immediately and without handling other related problems.
Partial fix for R9V-240531.
=> fix(security): remove double URL decode (921151 PL2, 932190 PL3, 942441 PL2, 942442 PL2, 942460 PL3)

.github/workflows/nightly.yml
- do not run scheduled in forked repos
- forks will get failures once a day trying to push to upstream coreruleset
=> fix: do not run scheduled in forked repos

.github/workflows/quantitative.yaml
This PR adds a new workflow where we run [go-ftw](https://github.com/coreruleset/go-ftw/commit/518e626c635075e70ee91cb8245c9b603174a381)'s quantitative testing feature.
=> feat: add quantitative testing to Git workflow

.github/workflows/quantitative.yaml
- adding comments from forks will fail unless we use the `pull_request_target` event
- quantitative run needs to add comments to the PR
=> fix: allow adding comments from forks

rules/restricted-files.data
Block file related to [CVE-2023-5003](https://nvd.nist.gov/vuln/detail/CVE-2023-5003), already actively accessed by bots.
=> feat: block CVE-2023-5003

tests/regression/README.md
Added `TX` variable `total_arg_length` with value `64000` because rule [920390](https://github.com/coreruleset/coreruleset/blob/main/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L881) uses that and its [test](https://github.com/coreruleset/coreruleset/blob/main/tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920390.yaml#L29) expects it. Without that a "regular" test is failed.
=> fix: add 'tx.total_arg_length' to rule 900005 for testing

tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
Added a test for 922130 for multipart formdata without any multipart headers.
=> feat: added empty multipart headers test for 922130

regex-assembly/941130.ra, rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941130.yaml
- change regular expression to not match any `=`
- add FP and true positive tests
Fixes #3961
=> fix: FP against `pattern` with `=` following at arbitrary position

renovate.json
The presets we use for renovate implicitly exclude the path `**tests**`, where the docker-compose file resides. This causes renovate to ignore the file for the docker-compose manager.
Explicitly override `ignorePaths` to fix this.
=> fix: enable docker-compose renovate manager properly

util/crs-rules-check/rules-check.py
It seems like in Python 3.13 the [re.sub()](https://docs.python.org/3/library/re.html#re.sub) syntax changed:
_Deprecated since version 3.13: Passing count and flags as positional arguments is deprecated. In future Python versions they will be [keyword-only parameters](https://docs.python.org/3/glossary.html#keyword-only-parameter)._
This PR aligns the `crs-rules-check` script and fixes the CI [errors](https://github.com/coreruleset/coreruleset/actions/runs/13437073040/job/37541853363?pr=4006#step:8:61).
=> fix: add argument name to function call

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921250.yaml
- prevent using cookie V1 protocol
- preventing cookie sandwich attacks
=> feat: prevent V1 cookie format use

rules/REQUEST-921-PROTOCOL-ATTACK.conf, tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921140.yaml
Response splitting can be achieved by injecting carriage return / new line characters at various places (headers, GET / POST arguments, cookies...). Some web servers or applications may be vulnerable to encoded injections (especially in URL paths), hence we explicitly decode URL encoding, where necessary.
httpd and nginx are not vulnerable to header splitting and will respond with status 400.
HTML entity decoding does not make sense in this context. No web server should ever decode HTML as part of the HTTP protocol. It is unclear why the original authors used `t:htmlEntityDecode` in some places, but at least in one test, a query argument separator (`&`) precedes a `%0d`, which leads to successful decoding of the escape sequence as HTML entity. This may explain an accidental use of …
=> fix: fix response splitting rules and tests

tests/docker-compose.yml
- add `debug` versions of base containers
- simplify local testing
=> chore: add debug versions for quick local testing

regex-assembly/933160.ra, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
- update regex to be more specific
- change from `.` (anything) to `[^)]`, which performs better while keeping the semantic
- follow standards
- optimize matching speed
- prevent potential backtrackings
=> fix(933160): use better regex

rules/lfi-os-files.data, rules/restricted-files.data, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930120.yaml, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930121.yaml
`.env` is probably the most generic entry in `lfi-os-files.data`. Unfortunatlye, since the words are matched using `@pmFromFile`, `.env` is easily matched as a substring. Most other entries are fairly unique or have a prefix or suffix that makes it unlikely for them to become FPs.
Note that `.env` is only commented out on purpose. `lfi-os-files.data` is also used as the base for other word files (e.g., `restricted-files.data` and since `.env` hasn't been an issue there until now, we don't want to remove it from those lists.
Fixes #3775
=> fix: remove .env from lfi-os-files.data

.github/workflows/test.yml, tests/regression/httpd-overrides.yaml
We currently override the test result for 920390 to expect an error because the httpd image segfaults on that test. The new images we are building no longer segfault, making the test fail. To resolve the situation, we'll disable the test until the new images have been released (the images are verified using the CRS test setup, which currently fails because the test _does not fail_).
=> chore: temporarily deactivate test for 920390

tests/regression/nginx-overrides.yaml
With the new images that we are about to release, the test for 920390 will finally work.
=> chore: update test setup for 920390

tests/docker-compose.yml
Testing 920390 requires`TOTAL_ARG_LENGTH` to be set to less than 6400.
=> test: set TOTAL_ARG_LENGTH for testing 920390

rules/restricted-upload.data
Dear coreruleset community,
After browsing the list of issues, I found [this one](https://github.com/coreruleset/coreruleset/issues/3916) that I can help with and familiarize myself with the contribution process.
I will first propose to refresh this data file by fixing and executing again the legacy script that I downloaded from previous version of this repository. I sorted the list alphabetically, in order to help the reviewer, here is the list of new keywords and the ones removed :
Added ✅ 
- .boto
- .envrc
- .fish
- .netrc
- .npmrc
- .selected_editor
- .svnignore
- .tmux.conf
- .vscode
- .yarnrc
- .zshenv
- BlockCypher.log
- cloud-config.yml
- compose.yaml
- compose.yml
- fish_variables
- ldap-authentication-report.csv
- secrets.json
- sendgrid.env
- user_secrets.yml
Removed ❌ 
- …
=> feat: refresh restricted-upload.data

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf
This PR adds header `x-middleware-subrequest` into `tx.restricted_headers_basic`, so it's going to be blocked by default. At first, we were considering to not block it by default (as it will disable some features of Next.js) but after it was [completely removed from Next.js](https://github.com/vercel/next.js/pull/77474), i suggest to just block it. If we do not agree on this, i can move it into `tx.restricted_headers_extended` which will block it from PL2.
Fixes: #4051
=> feat: block header related to CVE-2025-29927 (Next.js)

rules/REQUEST-901-INITIALIZATION.conf
It seems like we check the unset variable `TX:ENABLE_DEFAULT_COLLECTIONS` in [REQUEST-901-INITIALIZATION.conf](https://github.com/airween/coreruleset/blob/main/rules/REQUEST-901-INITIALIZATION.conf#L323).
This PR adds an extra check where we can be sure the variable is set or not, then we can get the value.
This needs because we the linter has a [step](https://github.com/coreruleset/crs-linter?tab=readme-ov-file#test-9---check-state-of-used-tx-variables) where we want to check this.
=> fix: added pre-check of unset TX variable

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf
Fixes #3143 
**Source**: Copilot chat
```
Here are some insights into potentially malicious file extensions from your list and why you should consider adding them to your Web Application Firewall (WAF) rules:
1. **`.hta` (HTML Application)**: These files can execute arbitrary commands and are often used in phishing attacks.
2. **`.reg` (Registry File)**: Can modify system registry settings, potentially introducing malware.
3. **`.sct` (Windows Script Component)**: Often exploited to execute malicious scripts.
4. **`.shs` (Shell Scrap Object)**: Can contain executable code disguised as harmless files.
5. **`.tmp` (Temporary File)**: While not inherently malicious, these files can be used to store malware payloads.
6. **`.ani` (Animated Cursor File)**: Vulnerabilities in `.ani` files have …
```
=> feat: add potential malicious file extensions into tx.restricted_extensions

.github/workflows/quantitative.yaml, .github/workflows/test.yml
This PR proposes making regression test runs across engines independent. Right now, if one engine test fails, the others are canceled. See for example https://github.com/coreruleset/coreruleset/actions/runs/14175241361/attempts/1.
Setting `fail-fast: false` would allow us to:
- Simplify detecting if a change is affecting only one engine or all of them. All the tests will individually succeed or fail, independently from the outcome of the others.
- See all the failing tests at once, avoiding having to eventually fix one engine and then having to rerun the tests to find further failings on other engines.
- In case of flaky results, rerun just the failing engine(s) and not the whole matrix.
- Bonus point: it will be even more beneficial when Coraza joins the matrix, enabling better …
=> ci: disable fail fast in regression tests, bump go-ftw

rules/lfi-os-files.data, rules/restricted-files.data, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930120.yaml, tests/regression/tests/REQUEST-930-APPLICATION-ATTACK-LFI/930130.yaml
Adds support for blocking compressed database dumps by adding `.sql.archive-extension`.
I used this list https://www.ncsc.admin.ch/dam/ncsc/de/dokumente/infos-it-spezialisten/govcert/govcert-ncsc_blocked-filetypes.txt.download.txt/govcert-ncsc_blocked-filetypes.txt for all of the archive filetypes, and then removed file formats that you typically won't use for this use case (For example there were some extensions for Unreal Engine, deb and rpm packages). I've left the niche archive types just in case somebody does use them.
=> feat: detect compressed database dumps

crs-setup.conf.example
Adds documentation on how to safely allow additional content types by enabling the appropriate request body parser to avoid a request body bypass.
=> docs: enable correct body processor when allowing content types

rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf, tests/regression/tests/RESPONSE-954-DATA-LEAKAGES-IIS/954100.yaml
Fixes #4077 
>Note: Drive letter and colon are not made optional.
=> fix(954100): detect forward slash in path

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf
Removes the `.application` extension from the restricted file extension list. I found this via an attack in my logs, but I don't think this attack should be blocked because of the file extension. As far as I can tell accessing this endpoint is perfectly legitimate, it has something to do with OWA and exports.
`GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application`
=> fix: remove `.application` from restricted extensions

regex-assembly/933160.ra, rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf, rules/php-function-names-933150.data, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933150.yaml, tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
Fixes a false positive when using `autodescription-site-settings[title_strip_tags]` as an parameter name in The SEO Framework plugin in WordPress by moving `strip_tags` to 933160.
=> fix: false positive with `title_strip_tags` by moving `strip_tags` to 933160

rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
For the regex used in 933151, the regex in the first chained rule contains a character class at the end:
`\b([^\s]+)\s*[(]`
However, removing the character class is better for performance (and arguably more readable):
`\b([^\s]+)\s*\(`
=> feat: remove unnecessary character class from 933151

regex-assembly/952110.ra, rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf, tests/regression/tests/RESPONSE-952-DATA-LEAKAGES-JAVA/952110.yaml
Adds a word boundary to 952110 to avoid non-java error messages from being matched.
=> fix: use word bondary on 952110 to avoid matching non-java errors

util/TESTS_EXCLUSIONS
The new [linter](https://github.com/coreruleset/crs-linter) needs this file.
Actually we use a [script](https://github.com/coreruleset/coreruleset/tree/main/util/find-rules-without-test) in our [CI](https://github.com/coreruleset/coreruleset/blob/main/.github/workflows/lint.yaml#L102-L106), which checks what rule does not have any tests.
The new linter is [able](https://github.com/coreruleset/crs-linter/pull/47) to do this job, but it needs an exclusion list - this file is it.
=> feat: add file which contains rule id's without tests

.github/workflows/lint.yaml, .pre-commit-config.yaml
- add pre-commit run
- move pre-commit out of lint so it is not run twice
- remove yaml lint from lint and execute as pre-commit
- fix files quickly
- update files after suggestions in code review
- Fixes #4174
=> ci: add pre-commit crs-toolchain run

tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941210.yaml, tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941330.yaml, tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942180.yaml
- move test wrongfully matching 942180 to 941210
- test is targeted to match xss not sqli
- #2471
=> fix(test): move xss test from 942180 to 941210

.github/workflows/lint.yaml
Improve the detection of the version that the linter should use to check the `ver` tags. We now check for:
- a version in the commit message: "...release...vx.y.z..."
- a version in the branch name: ".../release/vx.y.z"
- fall back to looking at the latest tag, as before
Fixes #4227
=> fix: fix linting of releases

.github/workflows/lint.yaml
Replace version detection in bash with the functionality in the new linter version.
=> chore: use new linter version

.github/workflows/lint.yaml
Use single quotes to prevent RCE from commit messages, e.g., when the
commit message includes backticks around words, which would be run in a
subshell when inside double quotes.
=> fix: update linter and fix commit message passing

crs-setup.conf.example, rules/REQUEST-901-INITIALIZATION.conf
Blocking the `.url` file extension causes false positives in the Nextcloud Bookmarks app when adjusting settings in the admin panel because of this URL path: `/apps/bookmarks/admin/settings/previews.generic.url`.
I can't think of any viable attack scenario that involves this file for an web application, this file type is primarily for linking to websites or email addresses on a desktop computer.
https://fileinfo.com/extension/url
=> fix: dont block `.url` file extension

rules/php-errors.data, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953100.yaml
This patch refines rule **953100 (PHP leakage)** by removing overly broad markers (`HY000`, `HY093`, `HY105`, `IM001`) from `php-errors.data` and replacing them with context-aware signatures:
- `SQLSTATE[HY000]`, `(HY000/`
- `SQLSTATE[HY093]`
- `SQLSTATE[HY105]`
- `SQLSTATE[IM001]`
These patterns align with real PDO/ODBC error messages while eliminating false positives caused by random substrings in response bodies (e.g. I had tokens like `hazhhy0004`,`sim001a`). This improves detection accuracy without weakening coverage of genuine leakage events.
=> fix(953100): remove generic SQLSTATE error codes causing false positives

regex-assembly/953101.ra, rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf, rules/php-errors-pl2.data, rules/php-errors.data, tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
This PR tries to reduce false positives with the PHP response rules at both PL-1 and 2 by moving false positive prone entries to PL-2 and using word boundaries where possible to reduce false positives.
=> fix: reduce false positives with php response rules
